### ISSUE TITLE
Race condition in Doppler under load

### ISSUE THREAD

**Issue by momchil-sap** [cloudfoundry/loggregator#105]
Hi,

We have a situation where our Firehose client suddently stops receiving log messages from Firehose without any error signalization in any of the components or in the client.

We are using the standard [noaa](https://github.com/cloudfoundry/noaa) client.

It is very easy to reproduce. One needs to deploy a Cloud Foundry system `v230` on `bosh-lite`, push an application that dumps an excess number of log messages (e.g. `5000 msg/sec`), and connect a number of Firehose clients with different subscription IDs. Having around `4` clients puts a good load on Doppler and reproduces it in less than a minute. Having the clients dump a `msg/sec` statistic to `stdout` makes it easy to track.

After some thorough investigation, we narrowed down the problem to Doppler. There is a race condition in the code that, as unlikely as it may seem, occurs quite often under heavy load. It results in a go-routine waiting on a channel that is never written to.

The problem is caused by the following line of code, that is replacing the `output` channel with a new one:
https://github.com/cloudfoundry/loggregator/blob/develop/src/truncatingbuffer/truncating_buffer.go#L101

Under load, the following line of code manages to consume the content of the old `output` channel and blocks on it before having the chance to pick the new one up:
https://github.com/cloudfoundry/loggregator/blob/develop/src/doppler/sinks/websocket/websocket_sink.go#L77

It seems unlikely as a race condition because it requires that the `websocket_sink` be able to loop through the whole `output` channel buffer, before the following piece of block finishes, but it happens.
https://github.com/cloudfoundry/loggregator/blob/develop/src/truncatingbuffer/truncating_buffer.go#L90-L98

I am working on a Pull Request that solves the problem and attempts to change as little code as possible. Unfortunately, the `truncating_buffer` is used by other packages and it will take some effort to align those as well.

This Issue is for tracking purposes and is a good place to get any remarks / comments on the matter prior to the Pull Request. (E.g. if there is already something under way or some restriction I should be aware of).

Regards,
Momchil

**Comment by Amit-PivotalLabs** [comment]
@momchil-sap do you have any logs from the doppler or nozzle at the time of this happening?  We're seeing this too, and I want to see if the logs you're seeing match what we're seeing, to assess if it's the same issue.

**Comment by Amit-PivotalLabs** [comment]
Here's a bit more info for what we see.  For one, seems perhaps coincidental, but a lot of the "all metrics disappear from a zone" or "all metrics reappear for a zone" happen around noon, give or take a couple minutes (Pacific time).  The other thing we see is in doppler, logs are full of "Output channel too full", both before and after the metrics disappear.  But, the frequency of those logs goes way up coincident with when the metrics disappear from DataDog.

```
 14570288=>2,
 14570289=>2,
 14570290=>3,
 14570291=>3,
 14570292=>1,
 14570293=>1,
 14570299=>6,
 14570303=>2,
 14570307=>1,
 14570310=>2,
 14570312=>2,
 14570313=>2,
 14570314=>2,
 14570316=>2,
 14570318=>2,
 14570328=>1,
 14570329=>2,
 14570332=>5,
 14570338=>1,
 14570341=>1,
 14570342=>2,
 14570343=>5,
 14570344=>3,
 14570345=>4,
 14570346=>1,
 14570347=>1,
 14570350=>3,
 14570351=>172,
 14570352=>395,
 14570353=>387,
 14570354=>399,
 14570355=>400,
 14570356=>474,
 14570357=>365,
 14570358=>403,
 14570359=>429,
 14570360=>377,
 14570361=>370,
 14570362=>89
```

We grouped "Output channel too full" log lines by `timestamp/100`, that's what you're seeing above. The timestamp/100 given by `14570351` is basically:

```
$ ruby -rtime -e 'p Time.at 1457035100'
2016-03-03 11:58:20 -0800
```

**Comment by momchil-sap** [comment]
Hi @Amit-PivotalLabs ,

I mostly did experiments on a bosh-lite setup to replicate it, though we have observed it on an actual system as well. I did not see any correlation with the time of day. I could replicate it any time I tried. You just had to put doppler under big enough load. (The more clients you had attached, the higher the chance) Tailing the logs of the `doppler` job would show a lot of `Output channel too full` logs, which would suddenly increase in number the moment the client stopped receiving any new logs from Firehose. This is in accordance to my race condition discovery. Since the `websocket_sink` is left blocked on the old channel, it never has the chance to read from the new one. This allows the `truncating_buffer` to fill the new channel much quicker and produce those log messages more often.

During my experiments I also had a piece of code that would prove that the race condition was occurring. It involved closing and setting to nil the old output channel in the `truncating_buffer` when doing a swap and then in the `websocket_sink` checking if there is a new output buffer here:
https://github.com/cloudfoundry/loggregator/blob/develop/src/doppler/sinks/websocket/websocket_sink.go#L79
If you ever get into a situation when there is (i.e. `<-buffer.GetOutputChannel()` does not return nil), then you have proven that the race condition is happening.

This implementation would actually solve the race condition bug in the `websocket_sink` but would cause other issues with the `syslog_sink`, as well as involve changes in the code of both sinks. This is why I reimplemented the whole thing in my pull request, so that no new changes are required in the sinks and the API remains mostly the same:
https://github.com/cloudfoundry/loggregator/pull/106

My experiments on bosh-lite showed that it fixes the issue. However, the unpredictability that caused the race condition would become part of the code. Meaning that it is unpredictable how the code would behave under load. It could go one of two ways, both of which are valid and produce correct output. 

This made unit testing unstable and I had to introduce a cheat to make it always go one way.

I fear that the same might be happening with the integration tests which are currently failing for the pull-request. Those will require some more investigation.

**Comment by momchil-sap** [comment]
By the way, I am not sure what is the benefit of dropping all the messages in the buffer. My pull request could be modified to work as a ring buffer, in which case messages would be gradually dropped one by one. Looking at the following article, I presume that was the initial intent for this buffer. Not sure what changed back then:
https://blog.pivotal.io/labs/labs/a-concurrent-ring-buffer-for-go
(The code in the article has a race condition, but that can be easily circumvented with a select statement as is done in the pull request)

**Comment by felixfriedrich** [comment]
How high is the load on your dopplers to run into the problem you've described? @momchil-sap 

Felix

**Comment by momchil-sap** [comment]
@felixfriedrich I haven't checked how back it goes version-wise but I presume it's the same with v228. 

To reproduce it, I run a single application on cf on bosh-lite dumping consistently around `5,000` log messages. The application is actually configured to write `10,000` logs/sec but `5,000` is the maximum throughput I get. I connect four firehose clients (based on [noaa](https://github.com/cloudfoundry/noaa))  that would regularly report received logs/second metric to stdout. 

After waiting a bit, the clients start reporting `0` one after the other. The fewer clients that are left, the lower the chance of the race condition, hence the higher the wait, but the first one should stop receiving logs within a minute. You could start 5 or 6 to be sure.

I use a somewhat fast machine with sufficient RAM.

**Comment by felixfriedrich** [comment]
Thanks! :-)

**Comment by wfernandes** [comment]
Fixed in https://github.com/cloudfoundry/loggregator/pull/106
