### ISSUE TITLE
High number of Loggregator to Doppler connections

### ISSUE THREAD

**Issue by momchil-sap** [cloudfoundry/loggregator#108]
Hi,

It seems that Loggregator would open new connections to all the Dopplers for each new `/firehose/<subscription>` connection.

A new `connector.Connect` method is called for each new connection:
https://github.com/cloudfoundry/loggregator/blob/develop/src/trafficcontroller/dopplerproxy/doppler_proxy.go#L163

Which in turn creates it's own Doppler connection list:
https://github.com/cloudfoundry/loggregator/blob/develop/src/trafficcontroller/channel_group_connector/channel_group_connector.go#L42

This means that if given `C` firehose clients, `L` loggregator instances and `D` doppler instances, you would end up with roughly `C x D / L` outbound connections from each Loggregator and `C` inbound connections for each Doppler. 

Is there a reason why those Doppler connections are not reused, which would result in `D` outbound connections from each Loggregator and `L` inbound connections for each Doppler? 

Assuming that the clients are likely to be more than the number of Loggregators, this should result in better numbers. You would have to do some log mapping / duplication in `Loggregator` which could increase the overhead there, but I have seen the CPU load on `Doppler` peek much quicker than on `Loggregator` right now, so that could balance the load.

Regards,
Momchil

**Comment by Jim-Campbell** [comment]
Thanks for filing this! We'll look at it in IPM Monday morning and prioritieze in our [backlog](https://www.pivotaltracker.com/projects/993188) then.

**Comment by Jim-Campbell** [comment]
Hi Momchil,

Sorry I left this so long. Your point is correct, and a good one. However, when I look at the numbers in use in a large system, I see the number of total connections an order of magnitude below our limits. For instance I've seen numbers like C=1000, D=20 and L=10. We'll keep this kind of analysis in mind as we grow to larger configurations, but for now the current implementation is sufficient given all the other feature work we'd like to spend velocity on.
