### ISSUE TITLE
Doppler should have configurable option to enable TCP keepalive for syslog endpoint

### ISSUE THREAD

**Issue by giner** [cloudfoundry/loggregator#11]
As syslog protocol does not provide any acknowledgement mechanism there should be an option to configure TCP keepalive for syslog endpoint to ensure (as much as possible) message delivery.

If TCP connection dies without acknowledgement then the rest of messages which are sent syslog endpoint will be lost until the connection is re-established (usually very long time). This may happen because of network disruption or when destination (usually load balancer) silently drops connection due to inactivity timeout.

**Comment by JohannaSmith** [comment]
@giner In Loggregator v100+, syslog responsibilities are broken out into [`scalable-syslog`](https://github.com/cloudfoundry/scalable-syslog). We no longer maintain writing to syslog through Doppler. I've dropped a scalable-syslog [issue](https://github.com/cloudfoundry/scalable-syslog/issues/14) to look into implementing this.
