### ISSUE TITLE
rsyslog: get rid of legacy format

### ISSUE THREAD

**Issue by giner** [cloudfoundry/loggregator#121]
[syslog_forwarder.conf.erb](https://github.com/cloudfoundry/loggregator/blob/master/jobs/metron_agent/templates/syslog_forwarder.conf.erb) contains legacy configuration options which are difficult to get right. The problem is that legacy style options (for example queue settings) apply for the next action defined after those options and do not apply to the rest. While for static configuration it might be okay, for dynamic (our case) it is very easy to break expected behavior.

Therefore the following way of configuration:
```
$ActionResumeRetryCount ...
$ActionQueueType ...
```
should be replaced by:
`action(... action.resumeRetryCount="..." queue.type="...")`

More information on the official web site: http://www.rsyslog.com/doc/v8-stable/configuration/action/index.html
> Statements modify the next action(s) that is/are defined **via legacy syntax** after the respective statement. Actions defined via the action() object are **not** affected by the legacy statements listed here. Use the action() object properties instead.

**Comment by apoydence** [comment]
Metron is no longer responsible for setting up rsyslog: https://github.com/cloudfoundry/syslog-release. This functionality is going to be removed from Metron.
