### ISSUE TITLE
support for BOSH zones

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/loggregator#122]
Hi,

when do you plan to add support for BOSH zones in this release? A lot of jobs here use zones and currently require manual configuration - meaning you have to create definition of a job per zone just to be able to manually specify different zone. This creates excessive bloat in deployment manifests...

**Comment by combor** [comment]
👍 for this, I even think that without template changes it wont be possible to deploy with BOSH AZ feature  . As I understand zone property is only available during deployment time and for instance if you hardcode z1 for metron and BOSH will decide to deploy it to z2 it will create a huge mess.

**Comment by Nino-K** [comment]
Hi @mtekel,

There has been discussion of migrating the CF components to use new BOSH 2.0 features including BOSH AZs. However, we have yet to switch to using the new feature set within CF as a whole. Once that is done, we will create relevant stories to properly configure Loggregator components.

At the moment support for BOSH zones has not yet been prioritized. For now I'm going to mark this as close however we have our eyes on it.

Thanks,
CF Loggregator
