### ISSUE TITLE
Set multiple endpoints for syslog drain

### ISSUE THREAD

**Issue by tcnksm** [cloudfoundry/loggregator#124]
(I'm not sure this is correct place to ask, if not tell me where to post)

When CF user run `create-user-provided-service` and configure log forwarding service, they can specify only one endpoint (like [syslog://logs.example.com]()). 

Some log service (e.g., Splunk) provides multiple endpoints for HA reason.  Now CF user can not specify multiple endpoint. This means when something wrong on one endpoint. Log will not be forwarded.

Do you have a plan to support multiple endpoints (load balancing) ?

**Comment by wfernandes** [comment]
@tcnksm Currently we do not support multiple syslog endpoints that can be bound with a single service. 

You could bind multiple syslog endpoints to an application. Loggregator will then forward logs to all connected user provided "syslog" services. So in the event one of the syslog endpoints does go down, Loggregator will continue to forward application logs to the other syslog endpoint. 

Hope this helps.

**Comment by tcnksm** [comment]
Thanks,

But in that case, same log will be sent to log service right ?

**Comment by wfernandes** [comment]
Yes. The logs will be duplicated to both syslog endpoints. Currently, we do not support load balancing app logs to a set of syslog endpoints.

**Comment by tcnksm** [comment]
Do you have a plan to work on that ? 
Or is it acceptable if I send Pull Request for that feature ?

**Comment by wfernandes** [comment]
We currently do not have a plan to support this. However, you are more than welcome to submit a PR :)

**Comment by tcnksm** [comment]
Thanks,

But we will discuss with team whether we should contribute it now or in future.
If we start to work it now, then I'll reopen this ticket.
