### ISSUE TITLE
Loggregator or MetronAgent is driving ETCD high CPU

### ISSUE THREAD

**Issue by JimmyMa** [cloudfoundry/loggregator#125]
After upgrade from v221 to v226, the average ETCD CPU usage got increased from about 30% to 75%. please see the attached ETCD CPU usage. We have verified that was not caused by HM, so it could be Loggregator or MetronAgent.

<img width="1358" alt="screen shot 2016-05-13 at 4 48 51 pm" src="https://cloud.githubusercontent.com/assets/5013209/15265098/40e3d762-19af-11e6-8c19-d536f7c0d3d5.png">

**Comment by wfernandes** [comment]
@JimmyMa

- Which environment is this in? 
- How many Etcds, Dopplers andTraffic Controllers are in this environment?
- What are the specs of the Etcd VMs?
- How many apps are running in this environment?
- Is it possible for us to log into the environment and do some troubleshooting?

**Comment by Jim-Campbell** [comment]
@JimmyMa Any chance for us to get some more data?

**Comment by JimmyMa** [comment]
Hi, sorry for the late reply.

1. How many Etcds, Dopplers andTraffic Controllers are in this environment?
  There are 1 Etcd, 34 Dopplers, 9 Traffic Controllers

2. What are the specs of the Etcd VMs?
The Etcd VM has 8G memory, and CPU with 4 cores, and each core is below:
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 45
model name      : Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping        : 7
microcode       : 0x70b
cpu MHz         : 2000.036
cache size      : 20480 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu de tsc msr pae cx8 apic sep cmov pat clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl pni pclmulqdq ssse3 cx1
6 pcid sse4_1 sse4_2 popcnt tsc_deadline_timer aes hypervisor lahf_lm arat epb pln pts dtherm
bugs            :
bogomips        : 4000.07
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual

3. How many apps are running in this environment?
There are about 100K running apps instances in the environment

4. Is it possible for us to log into the environment and do some troubleshooting?
Sorry, no.

Now we have deployed a standalone ETCD server for HM9K, and the original ETCD server is still for Loggergator, and the CPU usage of original ETCD server is about 60% now.

**Comment by Jim-Campbell** [comment]
@JimmyMa We have validated that if you have a multiple etcd configuration, then each Loggregator component (Metron, Doppler, Syslog Drain Binder, Traffic Controller) client will randomly choose one of the etcds at startup using the storeadaptor library. If you scale up the number of etcds, you should see the CPU load go down. We would love if you could share with us the result of the scaling exercise.
