### ISSUE TITLE
Need to use the cgo dns resolver when using Go 1.6+

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/loggregator#126]
When you switched to Go 1.6, you are using the Go based DNS resolver. This resolver has a few known issues and doesn't work well in many situations with Cloud Foundry. Most of the issues have been fixed with Go 1.7.

For the time being, most if not all Go based components have been using the C-based DNS resolver by adding `export GODEBUG=netdns=cgo` to their scripts.
You can see examples of this in the HM9000 and Diego scripts.

**Comment by iplay88keys** [comment]
@fraenkel thanks for pointing this out. However, is there an issue that you have encountered with Loggregator specifically?

**Comment by fraenkel** [comment]
Drain urls would fail if powerdns is listed before the remote DNS server.

**Comment by iplay88keys** [comment]
Looking at the [Loggregator](http://bosh.io/releases/github.com/cloudfoundry/loggregator?version=51) and [cf-release](http://bosh.io/releases/github.com/cloudfoundry/cf-release?version=237), it doesn't look like we include `powerdns`. I see that [bosh](http://bosh.io/releases/github.com/cloudfoundry/bosh?version=256.7) includes `powerdns`. Would that be an issue?

**Comment by fraenkel** [comment]
Yes. Anyone who deploys with BOSH can decide what DNS servers they use.

**Comment by iplay88keys** [comment]
We have created a [story](https://www.pivotaltracker.com/story/show/121622051) to add the temporary fix to our templates until we upgrade to Go 1.7.

**Comment by wfernandes** [comment]
@fraenkel We are working to fix this issue. Could you provide instructions on how to setup a bosh-lite environment that can display this bug? 
You mentioned configuring `powerdns` before the remote DNS server in BOSH. How would we do that?

**Comment by fraenkel** [comment]
bosh-lite doesn't expose dns via the manifest, but you could manually adjust your etc/resolv.conf

**Comment by cppforlife** [comment]
you should be able to set dns on a network subnet and see that its set by the agent in the container.

**Comment by apoydence** [comment]
We are upgrading to go 1.7. We expect this to resolve the issue.
https://www.pivotaltracker.com/story/show/128422331
