### ISSUE TITLE
Log forwarding issues

### ISSUE THREAD

**Issue by Infra-Red** [cloudfoundry/loggregator#128]
At current moment we are running load tests against our Cloud Foundry deployment. During tests our system can produce around 12000 logs/sec. We have configured `syslog_daemon_config` to forward all logs to ELK. At some moment we stop to get any logs and only `monit restart metron_agent` for each Cloud Foundry instance helps to resume logs forward process.
I believe that the bottleneck is somewhere between metron_agent and doppler. But also as i understand with `syslog_daemon_config` property enabled metron_agent only adds rsyslog template to `/etc/rsyslog.d` folder and all components logs must be forwarded via rsyslog daemon. So for me it is not clear how `monit restart metron_agent` can solve logs forwarding issue.

**Comment by wfernandes** [comment]
rsyslog does not forward component VM logs to the Loggregator system. Resetting Metron will also restart `rsyslogd`.

Metron is ([was](https://github.com/cloudfoundry/syslog-release)) used to configure the `rsyslogd`, but does not do anything with the data.
