### ISSUE TITLE
Syslog format (rfc) used

### ISSUE THREAD

**Issue by momchil-sap** [cloudfoundry/loggregator#134]
Hi,

I am trying to find out the RFC that is used to model the syslog messages, as configured here:
https://github.com/cloudfoundry/loggregator/blob/37043af8477dadbdcb3f6ab53880fa3bc63f76c3/jobs/metron_agent/templates/syslog_forwarder.conf.erb#L40-L55

This results in messages of the following form.

```
<pri>timestamp hostname app [key=value key=value] msg
```

This looks quite similar to [rfc5424](https://tools.ietf.org/html/rfc5424), though not quite. Following that RFC, the message should have looked more like the following.

```
<pri> timestamp hostname app [id key="value" key="value"] msg
```

(where I have omitted some optional fields to get it as close as possible)

Is some variant of [rfc3164](https://www.ietf.org/rfc/rfc3164.txt) used, with non-standardized timestamp and custom-format structured data placed at the beginning of msg, as part of msg?

I was searching around but couldn't find much information on the topic. If there is a standard, it might be good to have that documented somewhere so that consumers can rely on it.

Regards,
Momchil

**Comment by wfernandes** [comment]
@momchil-sap Our syslog messages are formatted using rfc5424. See [our syslog sink writer](https://github.com/cloudfoundry/loggregator/blob/develop/src/doppler/sinks/syslogwriter/writer.go#L64-L65).

**Comment by momchil-sap** [comment]
@wfernandes , is this for application or system logs? (Seems to be the doppler sink for application logs).

I was asking for component logs, where the following template is used:
https://github.com/cloudfoundry/loggregator/blob/develop/jobs/metron_agent/templates/syslog_forwarder.conf.erb#L39-L48

This template is used to send logs to a remote syslog server, as configured here:
https://github.com/cloudfoundry/loggregator/blob/develop/jobs/metron_agent/spec#L29-L47

**Comment by wfernandes** [comment]
@momchil-sap Yes. The code reference I provided was for application logs. 

Unfortunately, the syslog format for the component logs was added before my time and I can't seem to find a story relating to it either. We can work this issue as a bug to standardize the format.

Also just wanted to inform you that the Bosh team is actually taking responsibility for forwarding component logs to syslog in the future. This is their [syslog release](https://github.com/cloudfoundry/syslog-release/). We can coordinate with them to let them know of the format we standardize on since they pretty much used our `syslog_forwarder.conf.erb`.

**Comment by apoydence** [comment]
Is the `id` field intended to be `[msgid](https://tools.ietf.org/html/rfc5424#section-6.2.7)`?

If so, are we OK with setting it and not letting it be dynamic?

**Comment by wfernandes** [comment]
@momchil-sap Can you clarify what the `id` field would represent for a component log?

**Comment by momchil-sap** [comment]
Reading a bit into the [rfc5424](https://tools.ietf.org/html/rfc5424) specification, it seems that there can be more than one `SD-ELEMENT` (`[id key="value"]`) segment in a message.

> STRUCTURED-DATA can contain zero, one, or multiple structured data
   elements, which are referred to as "SD-ELEMENT" in this document.

It seems to serve the purpose of a flat metadata hash/object, where `id` is used to name the object. This would allow you to differentiate between multiple such objects in a syslog message and to know how to interpret them.

> An SD-ELEMENT consists of a name and parameter name-value pairs.  The
   name is referred to as SD-ID.  The name-value pairs are referred to
   as "SD-PARAM".

> SD-IDs are case-sensitive and uniquely identify the type and purpose
   of the SD-ELEMENT.  The same SD-ID MUST NOT exist more than once in a
   message.

If we were to take the above into considerationg, I guess the following structure would be valid and sematically correct.

```
[job name="api_z1" index="2"]
```

Note how `id` is set to `job` and `job` is renamed to `name`.

I'm no expert, so any better ideas are welcome.

**Comment by momchil-sap** [comment]
P.S. To be aligned with BOSH 2.0, `job` could be changed to `instance`.

**Comment by wfernandes** [comment]
@momchil-sap Thanks for the suggestions. We'll discuss it and bring this up with the BOSH team since they own the [syslog-release](https://github.com/cloudfoundry/syslog-release) which will be the supported way of configuring component logs through `rsyslog`.

**Comment by ahevenor** [comment]
@keymon & @momchil-sap - I scheduled an item to review final changes and merge in under https://github.com/cloudfoundry/loggregator/pull/166

**Comment by momchil-sap** [comment]
@ahevenor , I am sorry but I fail to see how the pull request #166 links to this issue.

This issue is concerned with the syslog format used to stream VM logs, whereas the pull request has to do with metrics.

I looked at the changes but could not find one that corresponds to the syslog config on the VM. It would be great if you could point to that change in case I have missed it.

**Comment by ahevenor** [comment]
@momchil-sap - that was a copy/paste error on my part. I meant to link this issue instead - https://github.com/cloudfoundry/syslog-release/issues/3

**Comment by keymon** [comment]
Sorry, I lost track here. Do you need my help or input?

**Comment by ahevenor** [comment]
All, I am closing this for housekeeping. Resubmit an issue if you still are having an issue.

THanks
Adam
