### ISSUE TITLE
Does not reconnect to etcd

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry/loggregator#146]
We have observed a bug when running metron via BOSH on Windows where metron sometimes starts before consul does and then does not successfully connect to etcd.

Repro steps:
- Deploy a VM (linux or Windows, doesnt matter) with metron & consul, and metron configured to use consul's DNS to resolve its etcd server
- Go onto the VM and stop metron & consul
- Start metron before consul
- Observe that metron will not connect to the etcd, not emit metrics for applications

**Comment by wfernandes** [comment]
@benmoss Just to clarify. To my understanding, BOSH respects the order of the templates/jobs in the manifest. That's why in our environments we specify `consul_agent` before `metron_agent` in the templates section. Can you verify the order of the jobs in your manifest?

**Comment by benmoss** [comment]
@wfernandes the [BOSH docs](https://bosh.io/docs/job-lifecycle.html) say that "`monit start` is called for each process in no particular order". i think it's just fallout from the current linux implementation that they happen to start in the order you specify in the manifest. 

the problem is that on Windows since we're not using Monit we don't have the same code paths for all this, so we end up with a race condition between metron & consul starting.

**Comment by ahevenor** [comment]
@benmoss it looks like this item was delivered and we now have a back off strategy for connecting to etcd. Let us know if you still have issues.
