### ISSUE TITLE
Update Traffic Controller README

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/loggregator#157]
Add `/set-cookie` endpoint to list of endpoints and describe its purpose.

It would be nice to also document the legacy endpoints that these endpoints are replacing.

All pull request authors must have a Contributor License Agreement (CLA) on-file with us. Please sign the appropriate CLA ([individual](http://cloudfoundry.org/pdfs/CFF_Individual_CLA.pdf) or [corporate](http://cloudfoundry.org/pdfs/CFF_Corporate_CLA.pdf)).

When sending signed CLA please provide your github username in case of individual CLA or the list of github usernames that can make pull requests on behalf of your organization.

If you are confident that you're covered under a Corporate CLA, please make sure you've publicized your membership in the appropriate Github Org, per [these instructions](https://help.github.com/articles/publicizing-or-concealing-organization-membership/).

**Comment by danielbayerlein** [comment]
@wfernandes I think the issue lapsed, see 7ae6fb7874002058a83a2d625bd359bbb41a134d
