### ISSUE TITLE
UsePreferredTags doesn't appear to work

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/loggregator#16]
I am using the `rlpreader` tool in `loggregator-release`:

https://github.com/cloudfoundry/loggregator-release/blob/9d8bca4af76a31b2cf90f65a56ae5d98fc80efb6/src/tools/rlpreader/main.go#L56

`UsePreferredTags` is set to `true` but I still get out messages where it appears to be using the old tags:

```
timestamp:1512078412945145820 deprecated_tags:<key:"deployment" value:<text:"docker-deployment" > > deprecated_tags:<key:"index" value:<text:"0" > > deprecated_tags:<key:"job" value:<text:"docker-job" > > deprecated_tags:<key:"metric_version" value:<text:"2.0" > > deprecated_tags:<key:"origin" value:<text:"loggregator.metron" > > counter:<name:"egress" delta:69 total:12883 >
```

**Comment by jasonkeene** [comment]
@bradylove and @JohannaSmith said they knew what was causing this behaviour. If this is indeed a bug a regression test should be added.

**Comment by JohannaSmith** [comment]
@jasonkeene I added some clarification in the tracker story.
