### ISSUE TITLE
LegacySelector is broken

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/loggregator#17]
I am requesting specifically logs using `LegacySelector`...

```golang
&v2.EgressBatchRequest{
	ShardId: buildShardID(),
	LegacySelector: &v2.Selector{
		SourceId: *podName,
		Message: &v2.Selector_Log{
			Log: &v2.LogSelector{},
		},
	},
	UsePreferredTags: true,
}
```

...yet I get back counters and things that do not match my `SourceId`:

```
&loggregator_v2.Envelope{Timestamp:0, SourceId:"", InstanceId:"", DeprecatedTags:map[string]*loggregator_v2.Value(nil), Tags:map[string]string(nil), Message:(*loggregator_v2.Envelope_Counter)(0xc42000e0b0)}
&loggregator_v2.Envelope{Timestamp:0, SourceId:"", InstanceId:"", DeprecatedTags:map[string]*loggregator_v2.Value(nil), Tags:map[string]string(nil), Message:(*loggregator_v2.Envelope_Counter)(0xc42000e0c0)}
```

If this is going to continue to be part of the API it needs regression coverage.

**Comment by enocom** [comment]
This is a mistake in the router component where `LegacySelector` is entirely ignored. See [here](https://github.com/cloudfoundry/loggregator/blob/29e2ab4407badeb3579abca38ccf852c0fe2915e/router/internal/server/v2/pubsub.go#L58-L72).

**Comment by JohannaSmith** [comment]
We fixed it by having the RLP convert a LegacySelector to a Selector. The router therefore does not have to concern itself with LegacySelectors.
