### ISSUE TITLE
Instance index not showing up in syslog drain

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/loggregator#173]
Running cf-release 245 and recommended Diego version.

Our system implements a syslog drain that does some processing of an applications loggregator messages prior to sending them into our log server.

It appears that with this the syslog drain isn't adding instance index for most/all log messages. 

* Under cf logs every message has an instance index.
* Under DEA only "App" has an instance index.
* Under Diego nothing has an instance index.

Here are example output I'm seeing.

cf logs:
```
2016-11-17T16:58:23.24-0700 [API/0]      OUT Updated app with guid 4d70b514-ed6a-48dc-aefa-2df2732093a7 ({"diego"=>false})
2016-11-17T16:58:23.24-0700 [DEA/0]      OUT Starting app instance (index 0) with guid 4d70b514-ed6a-48dc-aefa-2df2732093a7
2016-11-17T16:58:28.18-0700 [App/0]      OUT [CONTAINER] org.lds.cloudfoundry.jmxmp.JMXMPJavaAgent          INFO    Starting JMXMPJavaAgent on 'service:jmx:jmxmp://0.0.0.0:61012'
```

DEA syslog drain:
```
176 <14>1 2016-11-17T23:58:23.248806+00:00 loggregator 4d70b514-ed6a-48dc-aefa-2df2732093a7 [API] - - Updated app with guid 4d70b514-ed6a-48dc-aefa-2df2732093a7 ({"diego"=>false})
177 <14>1 2016-11-17T23:58:23.249556+00:00 loggregator 4d70b514-ed6a-48dc-aefa-2df2732093a7 [DEA] - - Starting app instance (index 0) with guid 4d70b514-ed6a-48dc-aefa-2df2732093a7
232 <14>1 2016-11-17T23:58:28.1895+00:00 loggregator 4d70b514-ed6a-48dc-aefa-2df2732093a7 [APP/0] - - [CONTAINER] org.lds.cloudfoundry.jmxmp.JMXMPJavaAgent          INFO    Starting JMXMPJavaAgent on 'service:jmx:jmxmp://0.0.0.0:61012'
```

Diego syslog drain:
```
223 <14>1 2016-11-17T23:58:53.178363+00:00 loggregator 4d70b514-ed6a-48dc-aefa-2df2732093a7 [APP/PROC/WEB] - - [CONTAINER] org.apache.coyote.http11.Http11Protocol            INFO    Destroying ProtocolHandler ["http-bio-8080"]
123 <14>1 2016-11-17T23:58:53.514233+00:00 loggregator 4d70b514-ed6a-48dc-aefa-2df2732093a7 [APP/PROC/WEB] - - Exit status 143
120 <14>1 2016-11-17T23:58:53.525619+00:00 loggregator 4d70b514-ed6a-48dc-aefa-2df2732093a7 [CELL] - - Destroying container
132 <14>1 2016-11-17T23:58:53.908535+00:00 loggregator 4d70b514-ed6a-48dc-aefa-2df2732093a7 [CELL] - - Successfully destroyed container

```

To duplicate:

1. Listen on a machine with netcat
```
nc -l 9050
```

2. Create a user provided service that drains logs to the machine you're listening on:

```
cf cups drain -l syslog://{youriphere}:9050
```

3. Bind this service to an application and make the application log.

Assert in your netcat output no instance information for any component when app running in Diego.

4. Switch application to DEA

Assert In your netcat only app has an isntance index.

5. `cf logs app --recent`

Assert that everything has an instance index.

It would appear that syslog drains are perhaps using some deprecated means to identify the origin and index.

I hope that syslog drain can be updated so that it gets index all the time like `cf logs` does.

**Comment by ahevenor** [comment]
@youngm I have scheduled this item for review in our backlog.

**Comment by youngm** [comment]
Thanks @ahevenor

**Comment by apoydence** [comment]
We have [updated](https://github.com/cloudfoundry/loggregator/commit/028a50724285c943bf39f18a928e878882966c69) the syslog writer to comply with Diego.

**Comment by youngm** [comment]
Thanks @apoydence ! I created a follow on issue to be considered at some point to add the index for all sources.

https://github.com/cloudfoundry/loggregator/issues/181
