### ISSUE TITLE
For log drains consider adding index to all sources that have an index not just APP index

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/loggregator#181]
This is a follow on issue to https://github.com/cloudfoundry/loggregator/issues/173.  It would be nice if syslog and http drains could provide the index of all the sources that have an index just like loggregator cli output provides today.

Thanks.

**Comment by ahevenor** [comment]
@youngm we are following up to make sure this is not a breaking change for other users before picking this up.

**Comment by youngm** [comment]
Understood.  Thanks @ahevenor

**Comment by jasonkeene** [comment]
@youngm To clarify, from your previous issue `cf logs` has the output:

```
... [API/0] ...
... [DEA/0] ...
... [App/0] ...
```

Logs via `cf logs` that come from API, DEA, etc have their instance index but with syslog/http drains they do not. So, you would like to see the bosh instance index in the syslog output to match the `cf logs` output?

**Comment by youngm** [comment]
@jasonkeene That is correct.

**Comment by ahevenor** [comment]
@youngm the original story for this got deleted but we are approaching a good time for us to take this on. I created a new story for tracking here - https://www.pivotaltracker.com/story/show/142994595

**Comment by ahevenor** [comment]
@youngm we are planning to ship this in the next version of Loggregator. That said, it will be part of [scalable syslog](https://github.com/cloudfoundry/scalable-syslog-release) which will only ship with cf-deployment.
