### ISSUE TITLE
Memory leaks in v63

### ISSUE THREAD

**Issue by scottschulthess** [cloudfoundry/loggregator#185]
We upgraded to 63 (I think from an old release, 34) and the doppler process grows until it uses all available ram  fairly quickly after a restart ~15 minutes or so
Attached is the doppler executable a pprof heap, thanks!
[doppler_dump.zip](https://github.com/cloudfoundry/loggregator/files/662221/doppler_dump.zip)

**Comment by ahevenor** [comment]
@scottschulthess do you have more details about your deployment. how many dopplers? how many syslog drains?

**Comment by scottschulthess** [comment]
1 doppler, 1 syslog drain. i'm closing this - it appears to be fixed in 70, but we are now running into some high memory usage.
