### ISSUE TITLE
HTTP/S Writer doesn't include the response status code nor the response body in the error

### ISSUE THREAD

**Issue by asafm** [cloudfoundry/loggregator#198]
The "https_writer.go" has the following code
```go
func (w *httpsWriter) writeHttp(finalMsg string) (byteCount int, err error) {
	resp, err := w.client.Post(w.outputUrl.String(), "text/plain", strings.NewReader(finalMsg))
	byteCount = len(finalMsg)
	if err != nil {
		return byteCount, errors.New("syslog https writer: failed to connect")
	}

	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		err = errors.New("Syslog Writer: Post responded with a non 2XX status code")
	}
	io.Copy(ioutil.Discard, resp.Body)
	resp.Body.Close()
	return byteCount, err
}
```

If the server you're posting the logs to returns an error in the form of non 2XX status code, it could really help the user to know the status code and the at least 500 chars of the response body.

So I suggest when doing errors.New(...) include the failed status code  and a truncate of the response body in length of the first 500 bytes.

**Comment by jasonkeene** [comment]
I think the status code should be included in the error text for sure. This would make debugging issues a lot easier. The body on the other hand might be a little bit of a security concern. It would allow third party servers to control the text of the error returned here. This will likely get written to disk as logs and can be used to do arbitrary code execution. It sounds far fetched, I know, but this has actually happened in the past with a vulnerability in how logs were being processed before written to disk.

Would status code be enough?

**Comment by asafm** [comment]
It's a start :)
You can ruin the "code" by prefixing it with a text and trimming it to 500
characters.
We (logz.io) send a good explanation json in case of invalid batch.
It will be quite hard to get the full picture without it.
WDYT?

**Comment by jasonkeene** [comment]
It appears we have not been entirely consistent with how we handle response bodies in error text.

I will discuss with the team.

**Comment by asafm** [comment]
You closed without elaborating on the last comment
