### ISSUE TITLE
Reverse Log Proxy insists on use of an ephemeral port

### ISSUE THREAD

**Issue by markstokan** [cloudfoundry/loggregator#20]
*Summary:*
The Loggregator Health Endpoint's configuration should be updated to set its listen port below 32768

*Details:*

We discovered this issue debugging a ERT 1.12.9 deployment failure where the reverse_log_proxy service failed to start.
bosh shows...
```
| loggregator_trafficcontroller/0 (fcd45b21-b07c-4ea5-87b4-8d96dd35f2cf)* | failing | us-central1-a | micro       | 10.0.4.21 |
```
monit shows...
```
Process 'reverse_log_proxy'         Execution failed
```
rlp.log shows...
```
2018/01/05 23:37:19 Unable to setup Health endpoint (localhost:33333): listen tcp 127.0.0.1:33333: bind: address already in use
```
On this host there was already a service bound to that port:
```
# lsof -Pni | grep :33333
rpc.statd   784          statd    8u  IPv4   9361      0t0  TCP *:33333 (LISTEN)
```
It's our understanding that Linux systems reserve a range of port numbers for "ephemeral" or "dynamic" use. You can discover this range by doing the following:
```
# cat /proc/sys/net/ipv4/ip_local_port_range
32768   60999

# cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by apoydence** [comment]
We moved the default port to 0. For checking health, one could do a losf to see where the health port was bound to and query from there. There is no reason to lock a user into a port for that.

https://github.com/cloudfoundry/loggregator/commit/febb1220ce61bc957156696391bbf34054a3c144
