### ISSUE TITLE
metron_agent hangs on startup

### ISSUE THREAD

**Issue by rwwohl** [cloudfoundry/loggregator#200]
Our metron agents occasionally panic/restart (panic: No dopplers listening on [udp]) due to slow disks on our etcd cluster.  We have noticed on the later releases of cf (currently we are on v247) a more serious issue, that sometimes the metron_agent after restarting from a panic, will hang.  

Normal restart after panic we usually see in logs:
Startup: Setting up the Metron agent
Connected to etcd
Listening on 127.0.0.1:3457
metron started

When it hangs on restart after panic we see the following:
Startup: Setting up the Metron agent
Connected to etcd

Thats it.  The process does not open a listener on 127.0.0.1:3457 at all and the stderr file will output forever a line of: failed to emit: EventWriter: No envelope writer set

monit status will show the process as running, so there are no further attempts to restart the process and we end up with a job with a broken metron agent and loss of logging until we manually intervene.

**Comment by ahevenor** [comment]
@rwwohl we have eliminated our dependency on etcd in metron because of state problems such as this. If you upgrade to >=CF251 this will be resolved.
