### ISSUE TITLE
Changes in communication of Doppler not reflected in documentation

### ISSUE THREAD

**Issue by holgero** [cloudfoundry/loggregator#202]
Hi,

There are some changes in the code which introduce so-called "diodes", but this is nowhere mentioned in the architecture on the README of the project. Do they replace the websocket communication between Doppler and Fire Hose or are they something else completely? (Also what are diodes doing in a metaphorical world of sinks/faucets/fire hoses? Is this also a change of the mental picture?)

So, could you please update the documentation?

Best Regards,
Holger.

**Comment by ahevenor** [comment]
@holgero 

Thanks for the question.

The diode is an implementation of a [circular buffer](https://en.wikipedia.org/wiki/Circular_buffer) for streaming data using gRPC that we use to prevent back pressure on the system. This was previously handled by the kernel shedding UDP packets but the diode gives us ability to emit metrics for drops in the buffer. 

I have scheduled some time to review our docs and diagrams which are out of date in this regard. Our intent is to move to a more straight forward computer science model (e.g. ring buffers, ingress, egress and loss) rather than create a metaphor. 

I am going to keep this item open until we have these updates in place.

**Comment by holgero** [comment]
Many thanks for the explanation. And I like the intention to go for a more straight forward model.

Are these metrics you mentioned already emitted? What is their name? Is dropping of messages in the diode related to the message on stderr "Dropped 1000 envelopes"? (The other issue I opened #204 ).

**Comment by ahevenor** [comment]
The transition of protocol from UDP to gRPC means that it's probably necessary to track both UDP and gRPC metrics to ensure that you are collecting all metrics for loss across upgrades . Here is what exists.

## Metron Dropped
`grpc.sendErrorCount (GRPC)`
`udp.sendErrorCount (UDP)`
## Doppler Dropped 
`doppler.shedEnvelopes (gRPC ingress)`

I believe we will also continue to emit the dropped messages to stdout but need to do some further research with the team and get back to you on #204 separately. 

We are also working on a proposal for a basic loggregator healthkit nozzle which would help operators make sense of this naming mess.

**Comment by holgero** [comment]
I can see only a few instances of the metric `udp.sendErrorCount` that were issued. (All at a similar time and all with comparatively low numbers (a few up to 14 max).
I guess it doesn't send a metric with value 0, when nothing has been dropped, right?

No metrics with the name `grpc.sendErrorCount` are visible at all. The same applies to the metric `doppler.shedEnvelopes`. I wonder if I am missing something in our nozzle. Does it make sense to check with `cf nozzle` if these metrics are there or is it probable that there is no metric issued?

**Comment by ahevenor** [comment]
@holgero FYI - I merged in a new README.

@jasonkeene - can you comment on @holgero's specific metrics question.

**Comment by jasonkeene** [comment]
It is possible that no metric is being emitted. These metrics are emitted as events when loss occurs. Using `cf nozzle -no-filter | grep grpc.sendErrorCount` will show you if you have any metrics with the name `grpc.sendErrorCount`.

**Comment by holgero** [comment]
Thank you! Didn't know about the `-no-filter` switch of `cf nozzle`. BTW: This made me curious, so I wanted to check if there were more useful options for the `cf nozzle` command, but I didn't find the help for `cf nozzle` (should I open another issue for that?)

**Comment by ahevenor** [comment]
@holgero - if you'd like to continue this discussion please ping us in our slack channel for faster resolution. I am closing this item.
