### ISSUE TITLE
Missing metric

### ISSUE THREAD

**Issue by holgero** [cloudfoundry/loggregator#203]
The [lists of metrics issued by loggregator](https://github.com/cloudfoundry/loggregator/blob/develop/docs/metric_descriptions.md) mentions a metric named "DopplerServer.TruncatingBuffer.totalDroppedMessages". I seem to be unable to find this metric in our InfluxDB. Is it still issued? A github search in this repository came up with calls to UpdateDroppedMessageCount only from tests, so I am wondering if it is still in use.

**Comment by jasonkeene** [comment]
`DopplerServer.TruncatingBuffer.totalDroppedMessages` is still being emitted: 

This is where the [metric is emitted](https://github.com/cloudfoundry/loggregator/blob/develop/src/truncatingbuffer/truncating_buffer.go#L126)
The prefix `DopplerServer` is defined [here](https://github.com/cloudfoundry/loggregator/blob/552de8713e12d39890679c212e043676e5043e09/src/doppler/main.go#L45) and used to initialize the metrics package [here](https://github.com/cloudfoundry/loggregator/blob/552de8713e12d39890679c212e043676e5043e09/src/doppler/main.go#L73).

The method you mentioned `UpdateDroppedMessageCount` is actually for the metric `messageRouter.totalDroppedMessages` which indeed doesn't appear to be called from anywhere outside of tests. I will add this to our backlog as a chore to remove and close this issue. If there is anything else please reopen.
