### ISSUE TITLE
Doppler stderr message "Dropped 1000 envelopes"

### ISSUE THREAD

**Issue by holgero** [cloudfoundry/loggregator#204]
Hi,

I can see many messages with the text "Dropped 1000 envelopes" in the stderr log file of my doppler instance in fast succession. Like this:
```txt
2017/02/01 13:54:40 Dropped 1000 envelopes
2017/02/01 13:54:40 Dropped 1000 envelopes
2017/02/01 13:54:41 Dropped 1000 envelopes
2017/02/01 13:54:41 Dropped 1000 envelopes
2017/02/01 13:54:44 Dropped 1000 envelopes
2017/02/01 13:54:44 Dropped 1000 envelopes
```

What does this mean? Is it a slow consumer? If so, how can I identify it? Or should I scale up the number of doppler instances?

Best Regards,
Holger.

**Comment by holgero** [comment]
Perhaps one more thing to mention, the traffic controller instances have also some strange entries in their stderr log files, like these:
```txt
2017/02/01 13:57:03 Error while reading from stream (<redacted>:8082): rpc error: code = 1 desc = context canceled
2017/02/01 13:57:03 Disconnecting from stream (<redacted>:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2017/02/01 13:57:03 Error while reading from stream (<redacted>:8082): rpc error: code = 1 desc = context canceled
2017/02/01 13:57:03 Disconnecting from stream (<redacted>:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2017/02/01 13:57:03 Error while reading from stream (<redacted>:8082): rpc error: code = 1 desc = context canceled
2017/02/01 13:57:03 Disconnecting from stream (<redacted>:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2017/02/01 13:57:03 Error while reading from stream (<redacted>:8082): rpc error: code = 1 desc = context canceled
2017/02/01 13:57:03 Disconnecting from stream (<redacted>:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2017/02/01 13:57:03 Error while reading from stream (<redacted>:8082): rpc error: code = 1 desc = context canceled
2017/02/01 13:57:03 Disconnecting from stream (<redacted>:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2017/02/01 13:57:03 Error while reading from stream (<redacted>:8082): rpc error: code = 1 desc = context canceled
2017/02/01 13:57:03 Disconnecting from stream (<redacted>:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2017/02/01 13:57:03 Error while reading from stream (<redacted>:8082): rpc error: code = 1 desc = context canceled
2017/02/01 13:57:03 Disconnecting from stream (<redacted>:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2017/02/01 13:57:03 Error while reading from stream (<redacted>:8082): rpc error: code = 1 desc = context canceled
2017/02/01 13:57:03 Disconnecting from stream (<redacted>:8082) (doppler.disconnect=false) (ctx.disconnect=1)
```

**Comment by jasonkeene** [comment]
These logs are generated when the diodes are shedding load. The logs from the TC indicated to me that perhaps they are having a hard time communicating with that doppler. `context canceled` should only happen when the deadline is hit for that context.

Is it a single doppler instance that are showing the dropped logs? Are there other doppler instances that do not show them? Did you try to restart this process? Is it a persistent issue? Are you receiving logs for apps normally via `cf logs`?

**Comment by holgero** [comment]
> Is it a single doppler instance that are showing the dropped logs? Are there other doppler instances that do not show them?

No, all 8 doppler instances show the same behavior. I did a count of that message in the doppler logfiles and I can see that with the update to cf-release v249 the number (of occurrences of the message)  increases from a few thousands to tens of thousands.

> Did you try to restart this process?

No, didn't restart yet. And which process should I restart? The dopplers or the traffic controllers?

> Is it a persistent issue?

I'd say so. I just checked on one of the dopplers, the number of "Dropped 1000 envelopes" messages was like this (I did a `fgrep 'Dropped 1000 envelopes' doppler.stderr.log | awk '{print $
1}' | sort | uniq -c`):
```txt
  18810 2017/02/02
 113525 2017/02/03
 230814 2017/02/04
 215562 2017/02/05
  84347 2017/02/06
```
So over the weekend it was already in the hundreds of thousands.

> Are you receiving logs for apps normally via cf logs?

Yes, cf logs works normally. (Just tried it out with a simple static buildpack app. I could see logs with `cf logs app --recent` and also when tailing logs with just `cf logs app`.)

**Comment by jasonkeene** [comment]
Thanks for the additional information. This is scheduled in our backlog so we will look into it further.

**Comment by apoydence** [comment]
We have a few more questions:

1. Do you have any firehose nozzles? 
2. Do you have an idea about how many logs are being emitted from all your apps (per second)?
3. How many TrafficControllers do you have deployed?
4. Do you have any syslog drains?

Note:
The `context cancelled` message implies a client connected to the TrafficController disconnected, so this is nothing to be too concerned about.

**Comment by holgero** [comment]
Hi,

> 1. Do you have any firehose nozzles?

Yes, two different nozzles with two instances each.

> 2. Do you have an idea about how many logs are being emitted from all your apps (per second)?

I had a look at the metric 'listeners.receivedEnvelopes' from the traffic_controllers. It has values (sum over all traffic controllers) of about 30k - 60k.

> 3. How many TrafficControllers do you have deployed?

We have four instances.

> 4. Do you have any syslog drains?

Yes, there are also syslog drains.


Something else: I did a little more digging into the problem and found out that there seems to be an issue with balancing the load between the trafficcontrollers. I looked at the cpu load and the metric "dopplerProxy.firehoses". There I could see that at some times one of the four trafficcontrollers got to serve all of our firehoses. This instance had also a cpu load of 100% at those times. But even serving two nozzles seemed to be too much for one trafficcontroller instance. I then decided to increase the VM size of the traffic controllers and now the problem looks much better. I am thinking about reducing the number of traffic controllers to two and increasing their VM size in turn even further. Do you think that makes sense?

**Comment by jasonkeene** [comment]
The "Dropped 1000 envelopes" is doppler shedding load. This is a result of too many message being written to it. I would recommend scaling dopplers up (horizontally) and see if you see these messages as frequent.

As far as the trafficcontroller disconnect issues: It is indeed bad that your load balancer is landing all the connections for the nozzles on the same trafficcontroller instance. You do not want this. You can try horizontally scaling out your nozzle to multiple connections so that it will balance the load. If you need help with doing this feel free to contact us on our [slack channel](https://cloudfoundry.slack.com/messages/loggregator/).

I am going to close this issue as it isn't a specific bug or problem that we can address in this forum. If the above does not remedy the issues you have been seeing, again feel free to contact us on slack.
