### ISSUE TITLE
TrafficController keep-alive timer not properly reset

### ISSUE THREAD

**Issue by bradylove** [cloudfoundry/loggregator#21]
The timer in the WebSocket keep-alive is not being reset properly which could trigger false disconnects.

See: https://github.com/cloudfoundry/loggregator/blob/7d94ce34fc8133cd029d83edfeaee3e3dfb1636c/trafficcontroller/internal/proxy/keepalive.go#L37

**Comment by enocom** [comment]
@bradylove Where should the reset go in your reading?

**Comment by bradylove** [comment]
We should be calling stop and ensuring the timer channel is clear before resetting. https://golang.org/pkg/time/#Timer.Reset

**Comment by bradylove** [comment]
I was mistaken and stop is being called.
