### ISSUE TITLE
inconsistencies between metron_agen spec, doppler spec and readme

### ISSUE THREAD

**Issue by paolostivanin** [cloudfoundry/loggregator#218]
On ``metron_agent`` part of loggregator v70 there are the following properties listed inside the ``metron_agent/spec`` file: ``metron_agent.etcd.client_{cert,key)``.
These properties can be found also on the [latest README (v79)]( https://github.com/cloudfoundry/loggregator/blob/v79/docs/cert-config.md) but if we look inside the [spec file](https://github.com/cloudfoundry/loggregator/blob/v79/jobs/metron_agent/spec) for v79 the aforementioned properties are not listed at all.
Is it a problem with the spec file or the readme?

Thanks

**Comment by paolostivanin** [comment]
On [jobs/metron_agent/spec](https://github.com/cloudfoundry/loggregator/commit/ea15dcb46048122f1a8d5d065109623b673d129a#diff-cb50426f1a73dd8b379cf398f8c2ffbc) the following props are listed as deprecated:
```
loggregator.etcd.require_ssl	
loggregator.etcd.machines
loggregator.etcd.maxconcurrentrequests
loggregator.etcd.ca_cert		
```

but on [jobs/doppler/spec](https://github.com/cloudfoundry/loggregator/blob/develop/jobs/doppler/spec) they are still written.

**Comment by apoydence** [comment]
@paolostivanin Doppler still uses etcd for two purposes:
1. Service Discovery - Doppler announces itself via etcd so TrafficController can find it
2. Syslog Drains - The SyslogDrainBinder writes the syslog drain locations (from the Cloud Controller) to etcd and Doppler uses them.

That said, the listed doc is invalid saying metron communicates with etcd.

**Comment by jtarchie** [comment]
@paolostivanin, we've updated the [docs](https://github.com/cloudfoundry/loggregator/commit/b71086b9b5418c396b0156fef7f4c4737a395762).

Thanks for pointing this out.
