### ISSUE TITLE
Invalid stderr message from metron

### ISSUE THREAD

**Issue by bradylove** [cloudfoundry/loggregator#226]
```
2017/03/14 15:53:57 failed to write to Doppler: write udp4 127.0.0.1:40736->127.0.0.1:0: write: connection refused
```

The destination address (`127.0.0.1:0`) should have a valid port. This code path would never work if it was trying to write to port 0, so it seems that the log messages is invalid.

/cc @apoydence

**Comment by jtarchie** [comment]
We see that this may occur in tests but not in production code. Closing until we see this happen in production code.
