### ISSUE TITLE
rlp tries to connect to missing dopplers too many times and fills the disk with error logs

### ISSUE THREAD

**Issue by tyyko** [cloudfoundry/loggregator#23]
During a deployment of cf-deployment, where we scaled down the number of dopplers, the reverse log proxies started to fill the ephemeral disk with log messages like:
```
Disconnecting from stream (10.0.65.86:8082) (doppler.disconnect=false) (ctx.disconnect=1)
Connecting to 32 dopplers
Unable to connect to doppler (10.0.65.84:8082): rpc error: code = Unavailable desc = grpc: the connection is unavailable
```

They produced hundreds of thousands of log messages per minute, eventually filling the ephemeral disk and crashing the VM.

Expected behavior would be to try to reconnect perhaps a bit slower and not writing so much in the logs.

**Comment by apoydence** [comment]
What version of Loggregator are you encountering this on?

**Comment by tyyko** [comment]
We tried both the v99 (version used in the etcd-removal migration steps) and the 101.4 (the one in cf-deployment 1.9.0)

**Comment by apoydence** [comment]
By the looks of it, that is a large deployment (32 dopplers). I'm assuming it has several consumers as well. For each consumer, the RLP will connect to each doppler. When the dopplers roll, those streams to the dopplers will die and the RLP will attempt to reconnect. It does so with some backoff strategy, however it looks like it is a bit chatty while doing so.

I think the solution here is to mute the logs.

**Comment by tyyko** [comment]
Thanks for your reply, I'm slowly getting a better idea of the flow of data, who connects to what, etc.

Talking about large deployments, in our biggest prod environment we have 32 dopplers (2cpu 4gb) scaled according to cpu/memory load but looking at the suggested formula in the [sizing guide](https://docs.cloudfoundry.org/loggregator/log-ops-guide.html#scaling):

_DopplerServer.listeners.receivedEnvelopes_ is 1,1k/doppler
_listeners.totalReceivedMessageCount_ (renamed to doppler.ingress with v101.4) is ~60k/doppler

we should have 61 dopplers.  

**Would you recommend to double the dopplers or can this break the application logging stack? There are ~6k syslog drains in that system.** As sidenote, dopplers CPU usage went from ~60% to ~100% after the migration to the new scalable-syslog system. But this can be also due to log-api/adapter backpressure as they where crashing due to memory and disk full.


_I set up now the smallest system possible:_ 
1 doppler, 1 log-api, 1 adapter, 1 application, 1 service binding, 10 logs/s

This is what I got:
 **adapters** writes about broken connection `Subscriber read/write loop has unexpectedly closed: rpc error: code = Internal desc = transport is closing` and a new connection (Created new connection to loggregator egress API) 10 times in one shot every 10 minutes.
**This means 20 lines of logs every 10 minutes.**

log-api are similar, but have 5 lines of logs for each connection:
```
2018/02/08 14:25:38 Disconnecting from stream (10.0.65.68:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2018/02/08 14:25:38 Subscribe error: context canceled
2018/02/08 14:25:38 Error while reading from stream (10.0.65.68:8082): rpc error: code = Canceled desc = context canceled
2018/02/08 14:25:38 Disconnecting from stream (10.0.65.68:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2018/02/08 14:25:38 Connecting to 1 dopplers
```
**This makes 50 lines of logs every 10 minutes.**

I tried to scale the application (and service binding), adapter and log-api to 2. No change in amount of logs.

I tried to scale up dopplers to 2 and this is what happened:

On ADAPTER:
_10 logs about broken connection, so far so good_
`515 2018/02/08 14:34:05 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.0.65.69:8082: getsockopt: connection refused"; Reconnecting to {10.0.65.69:8082 <nil>}`

_Then it started to complain about connection unavailable for certain binding (there are only 2) Please mind the first number is the line# of the log file_
```
527 2018/02/08 14:34:05 failed to open stream for binding 9fcc8762-e8b5-4f4e-bbb5-b42a7eb4f56e: rpc error: code = Unavailable desc = grpc: the connection is unavailable

52523 2018/02/08 14:35:57 failed to open stream for binding 2ccc7af2-726b-4920-8742-e36a64741a95: rpc error: code = Unavailable desc = grpc: the connection is unavailable

```
**So in less then 1 minute it wrote +50k lines of logs. 8.3MByte **

On RLP: 
```
  876 2018/02/08 14:35:23 Event from finder: {GRPCDopplers:[10.0.65.68:8082 10.0.129.69:8082]}
    877 2018/02/08 14:35:23 adding doppler 10.0.129.69:8082
    878 2018/02/08 14:35:23 Event from finder: {GRPCDopplers:[10.0.65.68:8082 10.0.129.69:8082]}
    
879 2018/02/08 14:35:23 adding doppler 10.0.129.69:8082

```
'Adding doppler' was repeated around 40 times in 1 second, then 
```
  920 2018/02/08 14:35:57 Connecting to 2 dopplers
    921 2018/02/08 14:35:57 Connecting to 2 dopplers
    922 2018/02/08 14:36:02 Connecting to 2 dopplers
    923 2018/02/08 14:36:02 Connecting to 2 dopplers
```

In this case RLP did not wrote much but adapter was way too verbose. As adapter logs contained the binding GUID I would assume this would scale with # of bindings. Also updating a bigger system takes more time usually so the window of time where this wave of logs comes would be bigger.

**Is it expected to see logs about broken connection every 10 minutes or is it something wrong happening?**
**Any comment on the huge amount of logs coming from the adapters? Did something went wrong with the backoff strategy?**

**How could we mute the logs?** I was not able to find a configuration parameter for adapters log-level in the [spec file](https://github.com/cloudfoundry/cf-syslog-drain-release/blob/develop/jobs/adapter/spec)

Thanks!

**Comment by thepeterstone** [comment]
Hi @tyyko, thanks for the detailed report.  We've removed some of the extraneous logging and verified the backoff strategy, so we're closing this issue.
