### ISSUE TITLE
[Breaking Change] Unable to receive logs due to CIPHER support

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry/loggregator#236]
PCF Upgrade 1.9 to 1.10 or any loggregator version after v68

After upgrading no logs were available, so I dig into the logs of traffic controller and I found

```
$cat loggregator_trafficontroller.stderr.log
2017/03/21 10:53:46 Could not get app information: [Get https://api.system.domain/internal/log_access/5aa0b3eb-8a45-480d-a7c5-2429c5293177: remote error: tls: handshake failure]
2017/03/21 10:54:21 Could not get app information: [Get https://api.system.domain/internal/log_access/5aa0b3eb-8a45-480d-a7c5-2429c5293177: remote error: tls: handshake failure]
2017/03/21 10:54:43 Error getting auth data: Post https://uaa.system.domain/check_token: remote error: tls: handshake failure
2017/03/21 10:54:56 Could not get app information: [Get https://api.system.domain/internal/log_access/5aa0b3eb-8a45-480d-a7c5-2429c5293177: remote error: tls: handshake failure]
2017/03/21 10:55:31 Could not get app information: [Get https://api.system.domain/internal/log_access/5aa0b3eb-8a45-480d-a7c5-2429c5293177: remote error: tls: handshake failure]
2017/03/21 10:55:43 Error getting auth data: Post https://uaa.system.domain/check_token: remote error: tls: handshake failure
2017/03/21 10:55:43 Error getting auth data: Post https://uaa.system.domain/check_token: remote error: tls: handshake failure
```

It seems that since **v68** the **TLS CIPHER** suite have been fixed to only two cipher because the default tls config
for the http client https://github.com/cloudfoundry/loggregator/commit/f629b09f75e64a3fb6f4fa2e3e9fa58abf6a1543# have been mutated to use plumbing.go which force these cipher

```
var supportedCipherSuites = []uint16{
	tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
	tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
}
```

That mean we need to force/change the TLS config on the SSL termination for CF Https (goRouter,LB) to support this two cipher .

Default Go httpClient support wider range of CIPHER so I guess that's why before v68 there was no issue.

Could be nice to be able to specify our own supported CIPHER or just go back to the default httpClient

@jasonkeene @ahevenor

**Comment by jasonkeene** [comment]
This issue was discussed in our IPM today. The team decided we should check in with the security team before moving forward. I have sent them an email, just waiting for a response.

**Comment by shinji62** [comment]
Thanks @jasonkeene again I think that supporting a little more could be nice.
If it's not possible just add to the documentation that we can avoid some bad effect.

**Comment by enocom** [comment]
@shinji62 This was reported again by another user. We have received feedback from our security team and will proceed with allowing operators to configure cipher suites via a bosh property.

**Comment by ahevenor** [comment]
@shinji62 we have discussed with security and will be moving forward to allow configuration of these cipher suites.

**Comment by shinji62** [comment]
Good to know thanks.

**Comment by shinji62** [comment]
@ahevenor What is the status of this issue, seems another user get the same issue.

The tracker story do not tell much about the actual status.

**Comment by ahevenor** [comment]
@shinji62 the story will add the ability to specify additional cipher suites when deploying loggregator. We have this at the top of our backlog but the packaging of a proper interface to allow for setting these ciphers will need to be completed separately.

**Comment by ahevenor** [comment]
@shinji62 this story is now up for testing. Is there a specific cipher suite that your load balancer is using I can use for my acceptance?

**Comment by shinji62** [comment]
Not really as I say we have already fixed that on the LB side.
Maybe you can check Haproxy default cipher

**Comment by ahevenor** [comment]
@shinji62 we have submitted a [private PR](https://github.com/pivotal-cf-experimental/pcf-patches/pull/52#issuecomment-296261892) for this to be backported. It will use the same `cipher_suites` property set for go-router. I am going to close this out of our issues. Please track through the backport PR.

**Comment by CAFxX** [comment]
I honestly think that breaking changes should be mentioned in the release notes... (yes, we also got bitten by this)

**Comment by ahevenor** [comment]
@CAFxX thanks for the feedback. I have updated release notes on all affected versions.
