### ISSUE TITLE
Adapters under load fills up memory and start swapping

### ISSUE THREAD

**Issue by tyyko** [cloudfoundry/loggregator#24]
We have a test system with 1000 deployed applications. Each application is bound to its own syslog drain service.

Starting with 2 adapter VMs (2 cpu, 4gb ram) we gradually increased the number of logs sent by the test applications and we experienced some memory issues in the adapters.

Increasing the load caused an increase of the memory usage up to 100% and made the VM start swapping.

The expected behaviour would be to drop incoming logs before starting to swap.

Doppler are 2 VMs 2cpu, 4gb ram each.

This was tested on loggregator-release v99 (the one used for etcd-removal migration) and the 101.4 (the one in cf-deployment 1.9.0)

**Comment by apoydence** [comment]
For each drain, two adapters will be assigned to read from the Loggregator system and write to the downstream drain.

This means with your cluster size of 2 adapters, each adapter will have a drain for each app. Each adapter uses a 10000 sized buffer for each drain:

```
1000*10000*256 => 2560000000B

or

2.38 GiB per adapter
```

(This assumes a 256 byte average for envelopes)

This doesn't leave much room for other memory usage. If you scale up the number of adapters, it will resolve the issue.

**Comment by tyyko** [comment]
Thanks for the info! I would close this in favour of #25 as you mentioned changing the logic under heavy load on both adapter and rlp. 

Would be cool to have this numbers you mentioned about cached envelopes in the docs as well!

Thanks and regards,
Michael
