### ISSUE TITLE
Traffic Controller seems to not be resilient to doppler failures when using BOSH Links

### ISSUE THREAD

**Issue by luan** [cloudfoundry/loggregator#257]
I have two dopplers on my environment, I disabled BOSH resurrection and stopped on of the VMs (in the infrastructure). As a result I can no longer get container metrics:

From TPS logs:
```
{"timestamp":"1492463022.880222321","source":"tps-listener","message":"tps-listener.fetching-container-metrics-failed","log_level":2,"data":{"error":"Error dialing trafficcontroller server: Get http://loggregator-trafficcontroller.service.cf.internal:8081/apps/ec666144-62c5-4e51-8e34-670e1caeb31f/containermetrics: net/http: request canceled (Client.Timeout exceeded while awaiting headers).\nPlease ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller endpoint is ws://loggregator-trafficcontroller.service.cf.internal:8081).","log-guid":"ec666144-62c5-4e51-8e34-670e1caeb31f"}}
```

And the seemingly corresponding TrafficController logs:
```
2017/04/17 21:03:32 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.0.32.10:8082: i/o timeout"; Reconnecting to {7052f9b2-3825-44f1-87a8-a36e1d4097f4.doppler.default.cf.bosh:8082 <nil>}
2017/04/17 21:03:32 error from doppler (7052f9b2-3825-44f1-87a8-a36e1d4097f4.doppler.default.cf.bosh:8082) while fetching container metrics: rpc error: code = 14 desc = grpc: the connection is unavailable
```

**Comment by jasonkeene** [comment]
I deployed cf-release with bosh DNS enabled and killed one of the dopplers. I see a lot of grpc connection errors coming from the traffic controller and for a few seconds container metrics requests hang and possibly timeout. However, after a few seconds container metrics start responding again without issue.

This turned out to be harder to reproduce than I thought.

**Comment by jasonkeene** [comment]
If you are using NOAA it does retry logic and will timeout and retry.

I'm going to close this for now. If you continue to see this please reopen.
