### ISSUE TITLE
rlp and traffic_controller should not be collocated

### ISSUE THREAD

**Issue by holgero** [cloudfoundry/loggregator#26]
With the current cf-deployment rlp and traffic_controller are collocated on a job called log-api.

This has several disadvantages:
* The requirements for scaling rlp's (https://docs.pivotal.io/pivotalcf/2-0/monitoring/key-cap-scaling.html#scalable-syslog) are different from the requirements for the traffic_controllers (https://docs.cloudfoundry.org/loggregator/log-ops-guide.html#scaling).
* If the rlp's fail to handle the log load, use up the memory on the VM and cause it to go into swapping (#25), the traffic_controllers are affected, too.
* traffic_controllers are not able to distribute the load caused by nozzles, so they need to be scaled up vertically, if they can't handle a load situation.
* rlp's can be scaled horizontally.

I am not sure if where I should reported this issue. The collocation is defined in cf-release, should I rather report it there?

**Comment by thepeterstone** [comment]
Hi @holgero,

RLP is not deployed with `cf-release`, so I'm assuming you're talking about `cf-deployment`.The default co-location is to help keep your VM count down in small deployments. For larger deployments, you can use an ops-file to deploy `traffic-controller` and RLP to different instance groups.

Hope this helps! If you need us to provide an example ops-file, please let us know.

**Comment by holgero** [comment]
Yes, you're right, I meant `cf-deployment`, sorry for the confusion.
OK, I understand the default is for small deployments. Fair enough. I guess we can write such an ops-file by ourselves. When we have it, we should perhaps contribute it. Would that make sense? (Not sure where it has to go, though. Would that be `cf-deployment` or here?)

**Comment by bradylove** [comment]
@holgero that great if you could contribute the ops-file. I would recommend opening a PR to `cf-deployment` once you have it.

**Comment by ahevenor** [comment]
I'd be curious to know more about your use case that you are running into this in, but I am going to close this issue out of our project. A PR into `cf-deployment` would be appreciated!

**Comment by holgero** [comment]
@ahevenor: I have written some context about our use case on the #loggregator slack channel. I thought I addressed you in that thread, is @hev your handle there?

**Comment by voelzmo** [comment]
/cc @dsabeti
> The default co-location is to help keep your VM count down in small deployments. For larger deployments, you can use an ops-file to deploy traffic-controller and RLP to different instance groups.

What is the target audience for cf-deployment? My impression was that even if you have some defaults that might not be well-suited for larger deployments, there should be some ops-files readily available to cover real production setups, right?

**Comment by holgero** [comment]
@voelzmo I opened a new issue on `cf-deloyment` to discuss this there: https://github.com/cloudfoundry/cf-deployment/issues/406 and asked a similar question.
