### ISSUE TITLE
Loggregator does not reconnect to doppler if idle connections timeout

### ISSUE THREAD

**Issue by martjarvi** [cloudfoundry/loggregator#262]
We have 2 trafficontrollers (both in 1 AZ). Same for dopplers. AZ-s are seperated by firewall what drops 24 old idle connections. Trafficontrollers does not reconnect and gives errors if it tries to retrieve logs via disconnected connection.

If doing cf logs myapp --recent it just hangs and gives the following error:

Error dialing trafficcontroller server: Get https://doppler.cfm.dev:4443/apps/38784616-1b5f-4cde-8c55-91e9af3ba8ad/recentlogs: net/http: request canceled (Client.Timeout exceeded while awaiting headers).
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller endpoint is wss://doppler.cfm.dev:4443).

In the trafficcontroller logs you can find something like this:

2017/05/08 07:15:05 Error while reading from stream (10.152.195.56:8082): rpc error: code = 1 desc = context canceled
2017/05/08 07:15:05 Disconnecting from stream (10.152.195.56:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2017/05/08 07:15:05 Error while reading from stream (10.151.195.59:8082): rpc error: code = 1 desc = context canceled
2017/05/08 07:15:05 Disconnecting from stream (10.151.195.59:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2017/05/08 07:15:22 error from doppler (10.151.195.59:8082) while fetching recent logs: rpc error: code = 4 desc = context deadline exceeded
2017/05/08 07:15:22 error from doppler (10.152.195.56:8082) while fetching recent logs: rpc error: code = 4 desc = context deadline exceeded
2017/05/08 07:15:22 recentlogs request encountered an error: context deadline exceeded

Is there a workaround to configure that trafficontroller tries to connect to only same AZ-s dopplers?

**Comment by jtarchie** [comment]
@martjarvi, can we confirm the following:

* What loggregator and cf-release version you are?
* How much traffic do you have on this system right now?
* How many firehose nozzles do you have running?

**Comment by martjarvi** [comment]
cf254. Its a test environment so there could be no traffic on weekends hence the 24h timeout and connection drop.

In the setup I had 2 trafficcontrollers and 2 dopplers, 1 in each AZ.

**Comment by jtarchie** [comment]
This is a bug that we need to investigate more. Thanks for the information.

**Comment by bradylove** [comment]
We did an experiment with loggregator v81 (version shipped with CF 254) against bosh lite with 1 trafficcontroller and 1 doppler. 

1. We verified we had connections from trafficcontroller to doppler with `lsof -c trafficco | grep doppler | wc -l`. 
1. We saw 20 connections from trafficcontroller to doppler. 
1. We stopped doppler (`monit stop doppler`) and saw the number of connections to doppler go to 0.
1. We started doppler (`monit start doppler`) and saw the number of connections go back to 20.

While this was going on, we ran the firehose example from [noaa](https://github.com/cloudfoundry/noaa/tree/master/samples/firehose) and saw expected behavior (data was coming out of firehose before and after restart of doppler).

@wfernandes

**Comment by bradylove** [comment]
@martjarvi Can you provide more information on the firewall rules so that we can more closely replicate your environment to try and re-produce this issue.

**Comment by bradylove** [comment]
@martjarvi Also, are you able to see data coming out of the firehose using the [CF Nozzle CLI plugin](https://github.com/cloudfoundry-community/firehose-plugin).
Once installed, run `cf nozzle -n`.

**Comment by martjarvi** [comment]
Hi.
Tested again
cf logs demo --recent (not working)
cf logs demo (working
cf nozzle 5 and cf nozzle -n both working.

Its external firewall between doppler and trafficcontroller so will ask the iptables equivalent rules.

**Comment by martjarvi** [comment]
Please put firewall between Trafficcontroller and doppler and add the rule in the firewall machine iptables --append INPUT --protocol all --src SRC_IP --dst DST_IP --jump ACCEPT. When the timeout occurs it should give the same situation hopefully. We have tested the problem with relayd.

**Comment by jtarchie** [comment]
@martjarvi, we were able to recreate your logs above.

1. Deployed a traffic controller and doppler.
2. Made sure that connections and data were established between the two.
3. On the doppler, we applied an `iptables` rule to `DENY` all packets from traffic controller.

These are the logs from traffic controller:

```
2017/05/23 17:58:43 Error while reading from stream (10.244.0.4:8082): rpc error: code = 1 desc = context canceled
2017/05/23 17:58:43 Disconnecting from stream (10.244.0.4:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2017/05/23 17:58:43 error receiving from doppler via gRPC context canceled
```

When we removed the `iptables` rule, the traffic controller indicated that the connections were broken.

```
2017/05/23 18:13:08 transport: http2Client.notifyError got notified that the client transport was broken read tcp 10.244.0.5:33050->10.244.0.4:8082: read: connection timed out.
```

The traffic controller automatically re-established the connection to doppler. Traffic controller was resilient to the loss of connection and re-established the connection when it could.

Please let us know if you something incorrect with the recreation. Please be aware, we are unable to recreate your firewall setup, so this is the closest recreation.

As a resolution, are you able to update your firewall so the connections between traffic controller doppler don't get reaped?

**Comment by martjarvi** [comment]
My setup is TC -> (FW machine) -> Doppler. If FW drops sessions, TC does not know that the 20 stateful tcp connections are not working anymore and I cant alter this behaviour. When I try cf logs demo --recent the TC tries to fetch the logs but fails and correctly states that the connection is broken.
2017/05/26 06:38:22 error from doppler (10.152.195.56:8082) while fetching recent logs: rpc error: code = 4 desc = context deadline exceeded
2017/05/26 06:38:22 recentlogs request encountered an error: context deadline exceeded
2017/05/26 06:38:24 transport: http2Client.notifyError got notified that the client transport was broken read tcp XXX:42958->YYYY:8082: read: connection timed out.

TC creates a new one like you said but before that I get the error :
Error dialing trafficcontroller server: Get https://doppler.cf.dev:4443/apps/6c4ec449-ec8a-473f-b40f-23590f41679c/recentlogs: net/http: request canceled (Client.Timeout exceeded while awaiting headers).
If I try this cf logs command many times (like 5-10) then sometimes it succeeds because it takes the new fresh connection but sometimes fails if it uses the old already invalidate connection and I get the timeout before TC creates a new connection. Eventually when excercising cf logs TC recreates all connections.

Maybe TC should send keepalives to these stateful connections?
