### ISSUE TITLE
Doppler memory leak when unbinding syslog drains

### ISSUE THREAD

**Issue by ahevenor** [cloudfoundry/loggregator#264]
If a large number of drains are setting up and tearing down syslog drains, doppler may experience high memory utilization. The memory for these drains is not be collected upon being unbound.

**Comment by ahevenor** [comment]
I am filing this as a known issue we discovered while testing the [scalable syslog release](https://github.com/cloudfoundry/scalable-syslog-release).

**Comment by bradylove** [comment]
@ahevenor I am going to close this issue since we have moved to scalable syslog.
