### ISSUE TITLE
Space-wide log forwarding

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/loggregator#27]
We have users that are very interested in the ability to have space-wide log/metric forwarding.

Ideally this should be possible using both currently-supported mechanisms: firehose and syslog forwarding:

- for firehose, an additional endpoint should be provided for all events generated in a space; this space firehose should be accessible by space developers/auditors/managers
- for syslog forwarding, there should be a way to bind a log forwarding service to a space (or, alternatively, to automatically bind a log forwarding service to any application created in that space)

 Originally brought up on https://cloudfoundry.slack.com/archives/C02HCCXV5/p1520393914000081

**Comment by ahevenor** [comment]
Another great suggestion we have just completed and I just have had the time to post to cf-dev. You can give this a try using the [cf-drain-cli](https://github.com/cloudfoundry/cf-drain-cli/releases/tag/v0.5). 

It does not yet collect metrics from service instances but we are working to make that happen as well (it needs some upstream ingress changes). 

I am closing this as well but feedback appreciated (post it on the cf-drain-cli repo).
