### ISSUE TITLE
Usage of metron/loggregator for BOSH deployments & service instances

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/loggregator#270]
We have some questions regarding the use of the metron/loggregator system in the following scenarios:

1. Will the CF components (CC, UAA etc.) eventually emit their logs through the firehose?
They already use metron agent to emit metrics but their logs are shipped nowhere unless the operator manually integrates something like the syslog release, logsearch-shipper or filebeat. 

These shipping tools mostly come from existing stacks, i.e. ELK. This basically requires us as the operator to build a complete logstash/rmq pipeline (since you want something that handles backpressure etc, right?) which replicates much of loggregator's functionality and purpose.

I guess the missing piece to use loggregator is something that takes the logs on the file system (or syslog) and sends it to metron agent or directly to loggregator.

If there is such a 'log shipping' mechanism provided by metron agent, we could also use this for our own BOSH deployments that emit logs and could consume everything over the firehose.

2. Customers like the way of streaming logs and metrics from their apps using `cf logs` or the firehose. They like to have the same mechanism (stream logs and metrics) for their (dedicated) service instances, i.e. a `cf service-logs`.

Would it be possible to leverage or extend the loggregator subsystem for that?
Since it already solves it for app instances, it offers the infrastructure and the knowledge (i.e. about CF's model, allowing it to authorize users easily) to add it without much effort.
If we build it ourselves, we basically end up writing everything from scratch since we can not hook into loggregator where needed (i.e. use a shipper, build a logstash pipeline, use a message queue per service instance to expose logs etc.).

From a first look glancing through the code, I assume logs/metrics for service instances could be added pretty easily; probably the loggregator api is already powerful enough to mark a log/metric for a service instance. So it would probably only need some endpoints on the trafficcontroller which expose the logs and authorize the users for the service instances?

I guess these are common use cases for CloudFoundry providers; it would be nice if we could leverage the existing metric/logging infrastructure for it.

**Comment by bradylove** [comment]
@ahevenor can you weigh in on this?

**Comment by ahevenor** [comment]
@MatthiasWinzeler thanks for this thoughtful submission and helpful feedback. These are strategic questions we discuss often internally. Here is some of our current thinking about these topics.

1. I see value in perusing the option of opting into this functionality. For larger deployments (with lots of metrics) this may stress the loggregator deployments, but for smaller deployments it makes total sense. Expanding the scope of the firehose limits our scaling ability so hence our logic for making this an opt-in feature (we also get feedback to separate what's in the firehose - see #155). This is not currently on our roadmap but I will bring it up in our planning discussions.

2. Timely suggestion. I have a [feature proposal](https://docs.google.com/document/d/1z5aVaUn0J3sG3q5tGB1viDxAF70HZ1BYnF9vUe-c0j4/edit#heading=h.efarh1epc9bb) for the concept of a developer segment firehose that does just what your describing. Appreciate you bringing this up and appreciate any input you have (please provide it in the document comments).

I am going to close this issue for tracking purposes but happy to continue the conversation here or on [slack](https://cloudfoundry.slack.com/messages/C02HCCXV5).

Thanks
Adam

**Comment by MatthiasWinzeler** [comment]
@ahevenor Thank you for your response - this sounds exciting.

I understand that currently there is no way to opt-in to add custom logs and metrics (also, since it might cause more load, there are no plans to feed the logs of the CF components to the loggregator subsystem).

However, in the feature proposal, it says:

> Several logs and metrics are already tagged appropriately to be identified as available to a developer assigned to a specific space. These include:
Dedicated service instance metrics
Dedicated service instance logs

This sounds to me like there is already a way to feed custom logs and metrics?

**Comment by MatthiasWinzeler** [comment]
@ahevenor, allow me to ping you on this...

I also found [service metrics for PCF](https://docs.pivotal.io/svc-sdk/service-metrics/1-5/index.html). Seems to be a way to feed service metrics into loggregator. Is this what you're referring to in the proposal? It does not seem to cover logs, though.

**Comment by MatthiasWinzeler** [comment]
Hi @ahevenor - let me ping you again for the question above. Any help appreciated!
