### ISSUE TITLE
Github Release 89 Packaging Bug

### ISSUE THREAD

**Issue by cholick** [cloudfoundry/loggregator#271]
With [89](https://github.com/cloudfoundry/loggregator/releases/tag/v89), the release size ballooned from 182MB to 747MB. Many things need to use the loggregator release (for metron agent), so this extra half gigabyte is really expensive as it's multiplied by lots of different components. It seems to be coming from `loggregator-acceptance-tests.tgz`, which is 527MB.

Can we get releases without this half-gig?

This might also be a bug with the release packaging script, as the source tree looks like it packaged itself recursively over and over again, with path likes:
`./loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src/loggregator/src....`

Uncompressed, the source tree for `loggregator-acceptance-tests` is 3.3G

**Comment by cholick** [comment]
Assuming a packaging bug, it would also be great to get the 89 bits released again without the extra half-gig.

**Comment by ahevenor** [comment]
Something seems off. Pulling this over to the top of the back log and adding a note to our release.

**Comment by ahevenor** [comment]
@cholick we just release Loggregator 89.0.1 to fix this.

**Comment by bradylove** [comment]
@cholick I would also add, v90 was also cut with this bug before we got a fix in place, we will apply a fix to it and cut v90.1 as well with the fix.

**Comment by cholick** [comment]
Thanks!
