### ISSUE TITLE
Local BOSH-lite deployment failures with loggregator releases > v89

### ISSUE THREAD

**Issue by mcwumbly** [cloudfoundry/loggregator#273]
We recently have started having problems deploying to a local BOSH-lite on VirtualBox.

The symptom was that uaa was failing in it's post-start script, but it looks like this was due to the VM being overloaded.

We see the problem with the following versions of CF-Deployment:

- `release-candidate` [49a9d51](https://github.com/cloudfoundry/cf-deployment/commit/49a9d51ae75bbafc2e1f5c1ba644e3d08afb4e7d)
- `master` [674c39f](https://github.com/cloudfoundry/cf-deployment/commit/674c39fbfc2cfaa5106b8de91ca063da4e40f697)

The previous commit on `master` works fine though:
- `master` [e82156e](https://github.com/cloudfoundry/cf-deployment/commit/e82156e0a1fa55d947ad016ef1ced3fe0d46401c)

The only difference is the loggregator release.  

We also confirmed that using an opsfile to set the version of loggregator back to v89 on the release-candidate branch of cf-deployment works:

```
- type: replace
  path: /releases/name=loggregator/version
  value: "89"

- type: replace
  path: /releases/name=loggregator/url
  value: https://bosh.io/d/github.com/cloudfoundry/loggregator?v=89

- type: replace
  path: /releases/name=loggregator/sha1
  value: 93af3cb98be40c0bc80916b1572f917585693494
```

When using newer versions of loggregator, aside from seeing the post-start failure in uaa, we notice the following:

- on the VirtualBox VM, the various `metron` processes are running with much more CPU than normal (~20% vs. ~2-5%)
- the size of the `metron_agent.log` grows more quickly and has many messages like this, that I don't see otherwise: `v2 egress dropped: unable to write to any dopplers`

/cc @dsabeti

**Comment by dsabeti** [comment]
@mcwumbly, now that you've mentioned the CPU usage, I wonder if this PR would fix the issue: https://github.com/cloudfoundry/cf-deployment/pull/165
(Also, it makes sense why you might see this on a local bosh-lite, but we don't see it in our pipeline.)

Essentially, by moving the dopplers up in the deploy order, the metron agents should be able to connect to dopplers immediately. A pair is working on this issue right now, so hopefully we'll know soon if this helps.

**Comment by mcwumbly** [comment]
@dsabeti looks promising!
