### ISSUE TITLE
Add more filtering capabilities to firehose

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/loggregator#28]
The current filtering capabilities on firehose are pretty limited; it is possible only to:
- receive all events
- receive only all logs (regardless of source and contents)
- receive only metrics

It is obviously feasible to filter after receiving from the firehose, but this limits operators' ability to create tailored, single-concern nozzles because having different nozzles receive all messages from a fat firehose puts undue burden on loggregator, routers and on the nozzle themselves.

As an example, if I want to process only [CELL] logs in my nozzle I would currently need to receive >40K event/s and then throw away >99.999% of them.

As an operator I would like to be able to specify, when connecting to the firehose, a filter composed of one or more of the following conditions:
- only events of a certain type (e.g. ContainerMetric, Log, ...)
- only events originating from a certain source (e.g. API, CELL, APP, RTR, ...)
- only log events whose payload match a certain pattern (ideally a regexp, but maybe a glob would be enough)

Initially mentioned on https://cloudfoundry.slack.com/archives/C02HCCXV5/p1520393914000081

**Comment by ahevenor** [comment]
@CAFxX Great suggestions! 

We have had this feedback from a few teams. Some of these suggestions are now implemented using the [v2 API](https://github.com/cloudfoundry/loggregator-api) in Loggregator [102.0](https://github.com/cloudfoundry/loggregator-release/releases/tag/v102.0). You can filter by envelope type (e.g. all counters) and even down to metric name. I don't think it currently supports source_id but I could be wrong. I could see us supporting the source filtering but I expect we'll probably push regex processing out to consumers. 

I am going to close this issue, but this is brand new last week and appreciate feedback and questions that come up.

**Comment by bradylove** [comment]
@CAFxX To clarify something on @ahevenor's response the V2 API can filter on Source ID, Envelope Type, Gauge Name and Counter Name.

**Comment by CAFxX** [comment]
@ahevenor I must be missing something... how can the v2 API be considered delivered if gorouter doesn't support gRPC? How are clients supposed to connect it? Moreover, from a cursory look to both sonde-go and trafficcontroller, it seems there's no trace of these new filtering capabilities there.
