### ISSUE TITLE
Metron can't reach doppler, fills up disk with logs

### ISSUE THREAD

**Issue by rainmaker** [cloudfoundry/loggregator#289]
Hello,

I came in this morning and saw that one of my CF installations had failed over the weekend. I triggered it again, and saw another fast failure. When I investigated, the failed VM had no ephemeral disk left (out of 4GB), and the culprit was a set of metron backup log files, with repetitions of the following lines:

```
2017/07/16 20:40:02 Failed to dial first-az.doppler.service.cf.internal:8082: context canceled; please retry.
2017/07/16 20:40:02 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: lookup doppler.service.cf.internal on 127.0.0.1:53: no such host"; Reconnecting to {doppler.service.cf.internal:8082 <nil>}
2017/07/16 20:40:02 error dialing doppler [first-az]doppler.service.cf.internal:8082: error establishing ingestor stream to [first-az]doppler.service.cf.internal:8082: rpc error: code = 14 desc = grpc: the connection is unavailable
```

I looked at consul's logs, and it may have been temporarily failing but was now unable to start due to the disk being full. I deleted all the backup logs and everything started successfully.

It would be helpful if this kind of failure resulted in fewer logs, so that the fix doesn't require manual intervention.

Thanks!

Raina
PCF Release Engineering

**Comment by apoydence** [comment]
This has been resolved by #274.
