### ISSUE TITLE
Traffic Controller seems to not be resilient to doppler failures

### ISSUE THREAD

**Issue by luan** [cloudfoundry/loggregator#291]
Using loggregator release v91 in a cf-deployment.

Running 2 dopplers, then disabling access to one of them with the following script:

```bash
for port in $(ss -lnp | grep LISTEN | grep -v "bosh-agent\|rpcbind\|rpc.statd\|sshd" | egrep '\*:[0-9]+' | awk '{ print $5 }' | cut -d ":" -f2); do
  echo iptables -D INPUT -p tcp --destination-port $port -j DROP
done | bash
```

After doing that we expect the system to recover but we see that the trafficcontrollers aren't ever giving up on the bad doppler:

```
2017/07/24 21:01:08 error from doppler (10.0.32.7:8082) while fetching container metrics: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/07/24 21:01:18 error from doppler (10.0.32.7:8082) while fetching container metrics: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/07/24 21:01:43 error from doppler (10.0.32.7:8082) while fetching container metrics: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/07/24 21:03:02 error from doppler (10.0.32.7:8082) while fetching container metrics: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

We're also running cf smoketests in a loop, and we see that it isn't able to get stats or logs for apps:

```
Could not fetch instance count: Server error, status code: 503, error code: 200002, message: Stats unavailable: Stats server temporarily unavailable.
Could not fetch instance count: Server error, status code: 503, error code: 200002, message: Stats unavailable: Stats server temporarily unavailable.
Could not fetch instance count: Server error, status code: 503, error code: 200002, message: Stats unavailable: Stats server temporarily unavailable.
1 of 1 instances running

App started


OK

App SMOKES-1-APP-3481ddef-ba39-4877-42a4-cc9dfd906164 was started using this command `bundle exec rackup config.ru -p $PORT`

Showing health and status for app SMOKES-1-APP-3481ddef-ba39-4877-42a4-cc9dfd906164 in org CF-SMOKE-ORG / space CF-SMOKE-SPACE as admin...
FAILED
Server error, status code: 503, error code: 200002, message: Stats unavailable: Stats server temporarily unavailable.

[2017-07-24 21:02:57.36 (UTC)]> cf app SMOKES-1-APP-3481ddef-ba39-4877-42a4-cc9dfd906164 --guid 
e9a26c35-f6cb-41d3-955d-d49113695c42

[2017-07-24 21:02:57.59 (UTC)]> cf logs SMOKES-1-APP-3481ddef-ba39-4877-42a4-cc9dfd906164 --recent 
Connected, dumping recent logs for app SMOKES-1-APP-3481ddef-ba39-4877-42a4-cc9dfd906164 in org CF-SMOKE-ORG / space CF-SMOKE-SPACE as admin...

FAILED
Error dialing trafficcontroller server: Get https://doppler.inconsulable.cf-app.com:443/apps/e9a26c35-f6cb-41d3-955d-d49113695c42/recentlogs: net/http: request canceled (Client.Timeout exceeded while awaiting headers).
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller endpoint is wss://doppler.inconsulable.cf-app.com:443).
```

**Comment by bradylove** [comment]
Hey @luan,

We have a fix going through the pipeline right now for this issue. The issue causing the `Client.Timeout` error is that our timeout in trafficcontroler was at 15 seconds while the CLI using noaa timed out in 10 seconds.

Our fix will remove the `Client.Timeout` error and could expose another issue.

If your deployment with 2 dopplers is deploying the dopplers to 2 different AZs, and you are setting up the `iptables` rules on the doppler in the same AZ as the diego cell that is hosting your application, then you will not see any logs when you do `cf logs` or `cf logs --recent`.

The reason for this is because the consul agent on that dopplers job is still reporting that doppler is healthy, and since metron tries to write to a doppler in the same AZ and uses consul for DNS it will attempt to write to the doppler and fail to do so due to the `iptables` rule.

We are going to discuss how we want handle and have a future story to address it.

**Comment by luan** [comment]
@bradylove that makes sense. I don't particularly care about logs going missing in these circumstances, I'd say that's expected. My problem was more with the whole thing not working at all. It seems like you have something that can help with it now.

What I'm still concerned with is that we don't give up on bad servers, so every user request will invariably take 5s now when you're in this situation? I'd say that's less then ideal but then again, if you have VMs down you're already in a less then ideal world anyway.
But do you think there may be a way to remedy that?

**Comment by bradylove** [comment]
@luan I agree that this is less then ideal, and is even a condition that could occur if you are scaling down dopplers and TCs have not yet been updated to remove those dopplers.

We do have some ideas on how we can resolve this, however they are not at the top of the list in priority at the moment.

**Comment by bradylove** [comment]
This has been accepted and will be in the next Loggregator release.
