### ISSUE TITLE
When doppler crashes, metrons connected to it get "stuck"

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/loggregator#298]
Last night it was reported by two community members that when a Doppler crashes, it will prevent metron from sending messages for 10-15 minutes. One of the reporters was on cf v252.

### Reproduction Steps

- On a doppler VM run: `echo c | sudo tee /proc/sysrq-trigger`
- On a VM with metron connected to that doppler run `netstat -ntap | grep DOPPLER_IP`

If this event occurs we should:

- Not leak connections.
- Recover quickly even under low load situations.

**Comment by giner** [comment]
Note: as of release v252 the impact of this issue is **lost of logs and metrics**. Components which send data to metron are not affected due to the absence of back-pressure on UDP protocol.

**Comment by bradylove** [comment]
The fix for this shipped with Loggregator 94.
