### ISSUE TITLE
Release and system logrotate rules result in file being left on disk

### ISSUE THREAD

**Issue by shashwathi** [cloudfoundry/loggregator#308]
Thanks for your submission!

Here are some guidance for submitting your issue.

Tell us why you are submitting?

- [x] I found a bug - here are some steps to recreate it.
- [ ] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [ ] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

This issue was initially raised on routing-release [here](https://github.com/cloudfoundry-incubator/routing-release/issues/81), looking at `metron_agent` templates it seems to be prone to the same issue since it is taking the same approach to configure the logrotate.

The metron agent job installs a cron task that runs logrotate on the files in /var/vcap/sys/log/metron-agent/*.log. At the same time there is the system wide logrotate running on the same files. The later has been installed by the bosh-agent. Also both logrotates are configured slightly different: The logrotate run by this cron job has the flag delaycompress whereas the system wide logrotate does not use this flag.

The logrotate job of the loggregator leaves a file metron-agent.log.1 in the monitored directory and the other logrotate job (configured through the bosh-agent) will copy that file to a file named metron-agent.log.1-2017xxxxxx.backup when it also does the rotation (this will happen if the metron-agent.log grew above the size threshold of 50MiB within the last 5 minutes). This file will remain in the directory and eventually the ephemeral disk of the VM will fill up. That in turn affects the processes on the vm.

Please review the comments on the [original issue](https://github.com/cloudfoundry-incubator/routing-release/issues/81) to suggested approaches to fix this issue.

We review issues and PR's on a weekly basis and try to schedule and prioritize
items. If you are wondering about status of an item feel free to contact us on
our [slack channel](https://cloudfoundry.slack.com/messages/C02HCCXV5).

Regards
@Nino-K && @shashwathi

**Comment by jasonkeene** [comment]
Cool, I will remove the logrotate cron from metron. It is not needed.
