### ISSUE TITLE
Health endpoints should be expvar (not prometheus) and use a scraper to get metrics out

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/loggregator#31]
If the loggregator system goes down, an operator would be forced to use its health endpoints to debug the issue. Therefore, we want to ensure that the metrics that loggregator emits are available on the health endpoint.

If we use the expvar forwarder, then we can ensure that every metric being emitted by loggregator is available on the health endpoints (for the synchronous data frame).

**Comment by bradylove** [comment]
This would have been really useful the last couple weeks while we have been debugging a couple of large bugs. Having a single source of info for metrics would have been nice especially where there was some confusion about the values being emitted for some more metrics. I feel like this would have made it easier to track down the bad actors.

**Comment by jtuchscherer** [comment]
CLosing pending more customer evidence this would be worth the effort.
