### ISSUE TITLE
Inconsistent handling of syslog drain URLs

### ISSUE THREAD

**Issue by altenhof** [cloudfoundry/loggregator#315]
We think we have found a bug on how syslog drain urls are handled in Doppler, more specifically in [sink_manager.go](https://github.com/cloudfoundry/loggregator/blob/develop/src/code.cloudfoundry.org/loggregator/doppler/internal/sinkserver/sinkmanager/sink_manager.go): 

For new app services the _parsed_ URL is used to register a new sink whereas for a removed app service the unparsed URL is used to find the corresponding sink.

This will of course fail if the drain URL contains any character sequence that would be unescaped. E.g., creating a user provided service with
```
cf cups bogus -l https://acme.org/foo%3Dbar
``` 
and binding an app with
```
cf bs myapp bogus
```
will eventually create a sink that is keyed with `https://acme.org/foo=bar`. This is due to the fact that the URL is run through a [blacklist check](https://github.com/cloudfoundry/loggregator/blob/develop/src/code.cloudfoundry.org/loggregator/doppler/internal/sinkserver/sinkmanager/sink_manager.go#L246).

Unbinding the app will make the sink manager try to [remove a sink that is keyed by the original URL](https://github.com/cloudfoundry/loggregator/blob/develop/src/code.cloudfoundry.org/loggregator/doppler/internal/sinkserver/sinkmanager/sink_manager.go#L222) which then silently fails.

Best regards

Michael Altenhofen
SAP SE

**Comment by enocom** [comment]
@altenhof Nice catch.

We've fixed this in 10fc21c695efa2abb6d342b9e73f6c9e0d920c90.
