### ISSUE TITLE
[question] cc.tls_port has no default

### ISSUE THREAD

**Issue by paolostivanin** [cloudfoundry/loggregator#318]
Why [cc.tls_port](https://github.com/cloudfoundry/loggregator/blob/develop/jobs/loggregator_trafficcontroller/spec#L122) has no default? 
The [cloudcontroller_ng](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/bosh/jobs/cloud_controller_ng/spec#L154) has a default value set to 9023, and I guess this would work for 99% of the people out there. 
Is there any technical reason why this value must be manually configured?

Thanks

**Comment by jasonkeene** [comment]
Sounds like a good idea. I know of no technical reason to not provide a default.

**Comment by paolostivanin** [comment]
Ok, cool. I can provide a PR tomorrow :)
