### ISSUE TITLE
`reverse_log_proxy` job fails with invalid certs

### ISSUE THREAD

**Issue by selzoc** [cloudfoundry/loggregator#321]
Unlike the `doppler`, `adapter`, or `scheduler` jobs, the `reverse_log_proxy` job will fail a deployment if it has invalid certs with a message much like:

`Error 400007: 'loggregator_trafficcontroller_z1/0 (67307835-7ada-49e3-9e25-c209dfb6ba44)' is not running after update. Review logs for failed jobs: reverse_log_proxy`

Of note is the fact that there are invalid certs for all of the other jobs as well, but they deploy successfully and merely log the errors.  It seems strange that there is this inconsistency.

**Comment by jvshahid** [comment]
verified the certs on the traffic controller job and it turns out they are invalid:

```
# openssl verify -CAfile /var/vcap/jobs/reverse_log_proxy/config/certs/mutual_tls_ca.crt /var/vcap/jobs/reverse_log_proxy/config/certs/reverse_log_proxy.crt   
/var/vcap/jobs/reverse_log_proxy/config/certs/reverse_log_proxy.crt: CN = reverselogproxy
error 20 at 0 depth lookup:unable to get local issuer certificate
```

it is also unclear whether this issue is about the invalid certs in `cf-release` or is trying to address the fact that some services started just fine with invalid certs ?

**Comment by jasonkeene** [comment]
@selzoc Are you sure that doppler, adpater, scheduler, etc do not fail? We just tested doppler by providing a CA that didn't sign the cert that it uses and it freaks out with:

```
2017/09/22 20:06:47 Could not use GRPC creds for server: x509: certificate signed by unknown authority
```

I think perhaps you just had doppler, adapter, scheduler, etc configured correctly and reverselogproxy was misconfigured somehow. I am going to close this issue. Feel free to re-open if you run into this again.

**Comment by selzoc** [comment]
@jasonkeene that's a very real possibility as the situation for bosh-lite certs (as you know) was so messed up.  thanks for the followup!
