### ISSUE TITLE
Application & cloud foundry Components log need to be trigged in ELK

### ISSUE THREAD

**Issue by wilfredwilly** [cloudfoundry/loggregator#34]
Hi All,

Following setup have been done for generating logs  to ELK

1) Links used to configured ELK  https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elk-stack-on-centos-7

2) for triggering logs from cloud foundry application setup used the following setup(Shipping to ELK)
https://logz.io/blog/cloud-foundry-elk-stack/

3)Logs haven't generated to ELK

Questions:
=======
Please let me know how to generate Application & cloud foundry Components log needed to be trigger in ELK

**Comment by ahevenor** [comment]
@wilfredwilly can you provide more details about the steps that are giving you trouble? For example, what command did you use to create the user provided service? what are you seeing if you run the command `cf services` ? 

You may also find the [cf-drain-cli plugin](https://github.com/cloudfoundry/cf-drain-cli) to be helpful.

**Comment by wilfredwilly** [comment]
Need to generate application logs which has been deployed under cloudfoundry To elk
Configuration done on server side:
=======================
input {
 tcp {
 port => 5000
 type => syslog
 }
 udp {
 port => 5000
 type => syslog
 }
 }
 
filter {
 if [type] == "syslog" {
 grok {
 match => { "message" => "%{SYSLOG5424PRI}%{NONNEGINT:syslog5424_ver} +(?:%{TIMESTAMP_ISO8601:syslog5424_ts}|-) +(?:%{HOSTNAME:syslog5424_host}|-) +(?:%{NOTSPACE:syslog5424_app}|-) +(?:%{NOTSPACE:syslog5424_proc}|-) +(?:%{WORD:syslog5424_msgid}|-) +(?:%{SYSLOG5424SD:syslog5424_sd}|-|) +%{GREEDYDATA:syslog5424_msg}" }
 }
 syslog_pri { }
 date {
 match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
 }
 if !("_grokparsefailure" in [tags]) {
 mutate {
 replace => [ "@source_host", "%{syslog_hostname}" ]
 replace =>[ "@message", "%{syslog_message}" ]
 }
 }
 mutate {
 remove_field => [ "syslog_hostname", "syslog_message", "syslog_timestamp" ]
 }
 }
 }
 
output {
 elasticsearch { hosts > ["localhost:9200"]}
 }
===================================================================
Following have been executed from client side.
================================
 cf cups test-log-drain -l syslog://Server-ip:5000
 cf bind-service test-log-drain
 cf restart cf-spring
[root@ip-172-31-30-130 CFAR]# cf services
Getting services in org techm_dev / space dev as admin...

name             service         plan   bound apps                                   last operation
test-log-drain        user-provided          console, Java-HelloWorld-Sample


But still logs are not getting triggered in ELK Dashboard.

**Comment by ahevenor** [comment]
What do you see if you run `cf logs --recent Java-HelloWorld-Sample`?

**Comment by wilfredwilly** [comment]
This is the output

 cf logs --recent Java-HelloWorld-Sample
Retrieving logs for app Java-HelloWorld-Sample in org techm_dev / space dev as admin...

**Comment by ahevenor** [comment]
Hmm. It doesn't seem like the app has succesfully started, what do you see when running `cf apps`?

**Comment by wilfredwilly** [comment]
Hi Ahevenor,

Need to view all cloud foundry application logs graphically in ELK(Elasticsearch, Logstash, and Kibana).
Issue:
In Cloudfoundry Application logs are not getting generated in ELK.



Warm & Regards,
Wilfred.C

**Comment by preettechm** [comment]
Hi Wilfred,
  Here is the resolution of your issue. You need to follow the following steps.

1- You need to configure your ELK on localhost only.. since we are using reverse proxy.
2- After creation of CF apps you need to create a service.
         $ cf cups logstash-drain -l syslog://[logserver]:5000
           // where [logserver] is the public IP of the ELK server

3- Now bind the CF application withe created service.
$ cf bind-service [app-name] logstash-drain

4- Restart the application 
$ cf restart [app-name] 


Wait for the couple of minutes then check in kibana dashboard. You can verify whether logs are created or not in this path as well "/var/lib/elasticsearch/elasticsearch/nodes/0/indices/".

**Comment by ahevenor** [comment]
As @preettechm points out, this should create thee drain binding and send the logs to elastic. Closing this issue.
