### ISSUE TITLE
By default, Agent waste a network call

### ISSUE THREAD

**Issue by enocom** [cloudfoundry/loggregator#4]
In [Loggregator Release](https://github.com/cloudfoundry/loggregator-release/blob/81169c2c697fe390cb0fd0be3db8c806e235b432/jobs/metron_agent/spec#L66), the agent is configured with an empty availability zone address by default. This means that when dialing the Router, the agent will waste a network call before trying the non-az address. See [here](https://github.com/cloudfoundry/loggregator/blob/8b4d239ef64dfeded08a22a9e1e61a4b37cc1933/agent/app/app_v2.go#L128).

/cc @JohannaSmith

**Comment by bradylove** [comment]
@enocom the config requires `RouterAddrWithAZ` to not be empty therefore that will never be an empty string.
