### ISSUE TITLE
Syslog drain binder bosh job config assumes Cloud controller is available via http

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/loggregator#43]
When in many cases it is not.

Should perhaps use `cc.srv_api_uri` instead?   Which, I believe, includes the preferred protocol and doesn't guess at the host name.

**Comment by jmtuley** [comment]
@zrob or @dieucao could you please confirm that this is the property we should use to locate CC?

**Comment by jmtuley** [comment]
Sorry that we let this fall through the cracks … but we've addressed this issue. (Please see the [Tracker story](https://www.pivotaltracker.com/story/show/89053898) for details.)
