### ISSUE TITLE
RLP Gateway + Auth Proxy has delays and partial messages

### ISSUE THREAD

**Issue by MasslessParticle** [cloudfoundry/loggregator#43]
When using curl to read messages from the `log-stream.<system-domain>` endpoint, we are noticing that there is a significant latency for envelopes to be egressed. The messages come out after a larger batch is available.

Often the batch is incomplete and the last envelope is truncated.

**Comment by bradylove** [comment]
This was resolved by moving the authentication in the RLP Gateway.
