### ISSUE TITLE
Missing CORS headers

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/loggregator#5]
Hi guys

We'd like to consume logs using the HTTP API from a SPA within the browser (where CORS applies). 
However, Chrome complains about some missing CORS headers and fails:

```
-- Request:
OPTIONS /set-cookie?CookieName=authorization&CookieValue=bearer+ey<oauth-token> HTTP/1.1
Host: doppler.<system-domain>
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Access-Control-Request-Method: POST
Origin: https://portal.<system-domain>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Access-Control-Request-Headers: content-type
Accept: */*
Referer: https://portal.<system-domain>/
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4

-- Response:
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://portal.<system-domain>
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Date: Mon, 30 Oct 2017 15:55:40 GMT
Set-Cookie: authorization=bearer eyJ<token>; Domain=doppler.<system-domain>; Secure
X-Vcap-Request-Id: 69cd55e4-2756-4225-62b4-485fab137a22
Strict-Transport-Security: max-age=15768000; includeSubDomains

-- Chrome Error:
Failed to load https://doppler.<system-domain>/set-cookie?CookieName=authorization&CookieValue=bearer+ey<oauth-token>: Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.
```

[Loggregator sets some CORS headers](https://github.com/cloudfoundry/loggregator/blob/8b4d239ef64dfeded08a22a9e1e61a4b37cc1933/trafficcontroller/internal/proxy/set_cookie_handler.go#L16-L18), however, `Access-Control-Allow-Headers` is missing. If we set it to `content-type` (on our LB that sits in between), it works fine.

Then, afterwards, we encountered the next CORS issue:

```
-- Request:
GET /apps/0ba1bea5-3f6f-4bb9-8303-9d861a0e4482/recentlogs HTTP/1.1
Host: doppler.<system-domain>
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
Origin: https://portal.<system-domain>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Referer: https://portal.<system-domain>/
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: authorization=bearer <oauth-token>

-- Response:
HTTP/1.1 200 OK
Content-Length: 692
Content-Type: multipart/x-protobuf; boundary=...
Date: Mon, 30 Oct 2017 16:03:07 GMT
X-Vcap-Request-Id: 60981205-e803-48f6-4f8a-58b5c55c4eb7
Strict-Transport-Security: max-age=15768000; includeSubDomains

-- Chrome error: 
Failed to load https://doppler.<system-domain>/apps/ebdb98db-2898-4012-8eaa-ccaa015254b0/recentlogs: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://portal.<system-domain>' is therefore not allowed access.

```

It looks like loggregator only sets CORS headers on `/set-cookie`. 
To satisfy the browsers' requirement, it would need it to add it to all responses to requests with HTTP header `Origin`. If we set the headers `Access-Control-Allow-Origin`, `Access-Control-Allow-Credentials` and `Access-Control-Allow-Headers` on all other responses, it works.

What do you think about adding these missing headers to loggregator?

**Comment by enocom** [comment]
@MatthiasWinzeler Thanks for the issue. We'll take a look at this at our next iteration planning meeting and talk about fixes. In the mean time PRs are always welcome.

**Comment by enocom** [comment]
@MatthiasWinzeler We've corrected our faulty CORS config in https://github.com/cloudfoundry/loggregator/commit/5ec073bb3cf2626a4724463540dc320d8e286616.

**Comment by MatthiasWinzeler** [comment]
@enocom Thank you! I will give it a try as soon as it lands in a CF release and let you know. You can close this issue.

**Comment by enocom** [comment]
@MatthiasWinzeler As of loggregator-release v99, we've stopped landing new features in cf-release in favor of cf-deployment. If this faulty config is a big problem, we're open to patching v99. 

/cc @ahevenor

**Comment by MatthiasWinzeler** [comment]
@enocom Thanks - I basically meant the next loggregator release, so it's fine for us.
