### ISSUE TITLE
Memory Leak in doppler and metron_agent?

### ISSUE THREAD

**Issue by libnux** [cloudfoundry/loggregator#53]
Hi,

I'm running a v205 CF deployment with ~350 application instances.

I just found that the doppler process on the doppler node and the metron_agent process on the gorouter node used too much memory(90.9% and 13.3 % respectively), as below.

Acutually, the memory usage of metron_agent was also >90%, and I restarted it yesterday, and just after 14 hours, the usage went up to 13.3%.

There are two doppler nodes and three gorouter nodes.

Process 'doppler'
============
  status                            Running
  monitoring status                 Monitored
  pid                               21648
  parent pid                        1
  uptime                            2d 11h 10m
  children                          0
  memory kilobytes                  14948028
  memory kilobytes total            14948028
  memory percent                    90.9%
  memory percent total              90.9%
  cpu percent                       12.5%
  cpu percent total                 12.5%

Process 'metron_agent'
==================
  status                            Running
  monitoring status                 Monitored
  pid                               28995
  parent pid                        1
  uptime                            14h 10m
  children                          2
  memory kilobytes                  2195608
  memory kilobytes total            2195608
  memory percent                    13.3%
  memory percent total              13.3%
  cpu percent                       6.8%
  cpu percent total                 6.8%

**Comment by myshkin5** [comment]
Hi @libnux,

What kind of log volume are you seeing? PWS has more Dopplers (by a factor of 10), but also has ~35 Kmsg/s – and our total memory usage on the doppler VMs hovers around 8% (and that's for **all** processes).

It may be that you're simply overloading the system and need to scale, but any additional information you can provide will help us to diagnose your issue and make recommendations.

Thanks!
@myshkin5 and @jmtuley (CF Loggregator team members)

**Comment by libnux** [comment]
@myshkin5, Thanks for the reply.

Could you please tell me how to get the message volume statistics? Should I enable the vartz port? 

By the way, for the metron_agent process running on gorouter vm, I changed code and embedded the pprof server, and got the heap profile as below, and for now the metron_agent process used ~1.9G memory.

The full heap profile is put here: https://drive.google.com/file/d/0B34qJfEMiowScjdOaFNrenFsSDA/view?usp=sharing

Memory Usage
=============
Process 'metron_agent'
  status                            Running
  monitoring status                 Monitored
  pid                               22777
  parent pid                        1
  uptime                            13h 10m 
  children                          2
  memory kilobytes                  1916996
  memory kilobytes total            1916996
  memory percent                    11.6%
  memory percent total              11.6%
  cpu percent                       6.9%
  cpu percent total                 6.9%
  data collected                    Wed, 03 Jun 2015 10:07:59 CST

Heap Summary
======
# runtime.MemStats
# Alloc = 6081816
# TotalAlloc = 448534263816
# Sys = 17905912
# Lookups = 67
# Mallocs = 5392507815
# Frees = 5392465930
# HeapAlloc = 6081816
# HeapSys = 14204928
# HeapIdle = 7749632
# HeapInuse = 6455296
# HeapReleased = 7585792
# HeapObjects = 41885
# Stack = 475136 / 475136
# MSpan = 64584 / 163840
# MCache = 1200 / 16384
# BuckHashSys = 1745968
# NextGC = 11756624
# PauseNs = [2644122 2648956 2701642 2595170 2649505 2698245 2577776 2586622 2712444 3099578 2586884 2720214 2602789 2632784 2648621 2638806 2690369 2572854 2575342 2569649 2624596 2591227 2595087 3749689 2612099 2593863 2595390 2708390 2956508 2576111 2610321 2596914 2698737 2902983 2659208 2808126 2650511 2551883 2533706 2827763 2549484 2672683 2640681 3701392 2687899 2684893 2530361 2761724 2551262 2753322 2750079 2587773 2667754 2573385 2617213 2612806 2616340 2661889 2576696 2688678 2627209 2622363 2583846 2718343 2666222 2612404 2695913 2601597 2504823 2551073 2929154 2513700 2395452 2186770 2560212 3112314 1879384 1800262 2133303 1644148 2216332 2653096 2503447 2846783 2518910 2613707 3753585 2572723 2681071 2717384 2786714 2949605 2610163 2880346 2556471 2600912 2600737 2690731 2738091 2801368 2948368 2543236 2600737 2550760 2719876 2607638 2637231 2637330 2736828 2627458 2668628 2630961 2585817 3150420 2828672 2616262 2717289 2957451 2553534 3719548 2640548 2805713 2755718 2791889 2617406 2715440 2836304 3013155 3133356 2612446 2706103 2612979 2702752 2871763 2573410 2573614 2614710 2623771 2579825 2540106 2574485 2618940 2709737 2631923 2643028 2600739 2551530 3592355 2575400 2609333 2602520 2626952 2600744 2570669 2605407 2638286 2723154 2655363 2820347 2598078 2590039 2641696 2694415 2601388 2600176 3329871 2579668 2623797 2907449 2615064 2616174 2611241 2673934 2635768 2635916 2816675 2809555 2622566 2591738 2819028 2656896 2775116 2966975 2706962 2646138 2617163 2583059 2781802 2711454 2612683 2629521 2650572 2600147 2638507 2605126 2596646 2596665 2600521 2634917 2554040 2595247 2581038 2573879 2548817 2781270 3053692 2675557 2678974 2581245 2665314 2575774 2613405 2570839 2563875 2733588 2619269 2582350 2706420 2645091 2668351 2597384 2667006 2777688 2693391 2606256 2571373 2590506 2599625 2588560 2746134 2660969 2634872 2588304 2653056 2582258 2862652 3017490 2619516 3085653 2632746 2605474 2664797 2591242 2725374 2578338 2629375 2588388 2669891 2622224 2550331 2533936 2572978 2626918 3289944 2696066 2727759]
# NumGC = 225465
# EnableGC = true
# DebugGC = false

**Comment by libnux** [comment]
Here is the svg file for the alloc_space heap profile: https://drive.google.com/file/d/0B34qJfEMiowSRVFOQ1lPNkZqZDg/view?usp=sharing

**Comment by libnux** [comment]
Following are the memory statistics  of the top 20 calls:
<pre>
(pprof) top20
533.45GB of 581.94GB total (91.67%)
Dropped 206 nodes (cum <= 2.91GB)
Showing top 20 nodes out of 88 (cum >= 4.14GB)
      flat  flat%   sum%        cum   cum%
  161.51GB 27.75% 27.75%   161.51GB 27.75%  fmt.func·001
   71.85GB 12.35% 40.10%    71.85GB 12.35%  bytes.makeSlice
   63.73GB 10.95% 51.05%   486.16GB 83.54%  fmt.Sprintf
   40.57GB  6.97% 58.02%   286.99GB 49.32%  github.com/gogo/protobuf/proto.CompactTextString
   34.56GB  5.94% 63.96%    34.56GB  5.94%  fmt.(*fmt).padString
   30.22GB  5.19% 69.15%    30.22GB  5.19%  fmt.(*pp).Write
   29.52GB  5.07% 74.23%   331.27GB 56.93%  github.com/davecgh/go-spew/spew.handleMethods
   15.55GB  2.67% 76.90%    15.55GB  2.67%  reflect.packEface
   14.72GB  2.53% 79.43%    14.72GB  2.53%  reflect.(*structType).Field
   12.94GB  2.22% 81.65%    12.94GB  2.22%  fmt.(*fmt).pad
   10.49GB  1.80% 83.45%   342.79GB 58.90%  github.com/davecgh/go-spew/spew.(*formatState).formatPtr
    7.42GB  1.27% 84.73%     7.42GB  1.27%  github.com/davecgh/go-spew/spew.NewFormatter
    5.95GB  1.02% 85.75%     6.10GB  1.05%  github.com/gogo/protobuf/proto.(*Buffer).EncodeStringBytes
    5.83GB  1.00% 86.75%   383.98GB 65.98%  fmt.(*pp).doPrintf
    5.65GB  0.97% 87.72%    18.72GB  3.22%  metron/eventlistener.(*eventListener).Start
    5.36GB  0.92% 88.65%    17.07GB  2.93%  github.com/gogo/protobuf/proto.UnmarshalMerge
    4.67GB   0.8% 89.45%    11.92GB  2.05%  github.com/cloudfoundry/dropsonde/signature.SignMessage
    4.61GB  0.79% 90.24%   220.24GB 37.85%  github.com/gogo/protobuf/proto.writeAny
    4.16GB  0.72% 90.95%     4.16GB  0.72%  reflect.New
    4.14GB  0.71% 91.67%     4.14GB  0.71%  github.com/gogo/protobuf/proto.(*Buffer).EncodeVarint
</pre>

**Comment by libnux** [comment]
The doppler process got restarted after eating up all memory:
<pre>
Process 'doppler'
  status                            Running
  monitoring status                 Monitored
  pid                               6902
  parent pid                        1
  uptime                            1h 28m 
  children                          0
  memory kilobytes                  2851448
  memory kilobytes total            2851448
  memory percent                    17.3%
  memory percent total              17.3%
  cpu percent                       12.5%
  cpu percent total                 12.5%
  data collected                    Wed, 03 Jun 2015 14:25:52 UTC +8
</pre>

**Comment by kicombs** [comment]
Hi @libnux,

CF v205 does have some memory inefficiencies when compared to the latest version of CF. For example, v205 would have been gathering per-application metrics in the Metron and Doppler components. We know that per-application metrics causes increased memory footprint and instability, and this issue was addressed by v211. Other memory instabilities were also addressed between the v205 and v211 releases.

We recommend upgrading to the newest CF version (currently v211) and see if the newer version solves your problem. If it does not, please be sure to let us know.

If upgrading is not immediately available to you, you could try to scale up the number of Dopplers and see if that helps your memory usage issue.

Thank you and let us know how it goes,
@kicombs and @myshkin5

**Comment by libnux** [comment]
Hi @kicombs ,

The issue was finally resolved by adding CGO_ENABLED=0  when build:

CGO_ENABLED=0 go build ......
