### ISSUE TITLE
noisy logs of traffic controller: error receiving from doppler via gRPC context canceled

### ISSUE THREAD

**Issue by giner** [cloudfoundry/loggregator#54]
Every time cf cli disconnects from traffic controller (ctrl +c) the following appears in traffic controller logs:
```
2018/10/16 07:34:44.509399 error receiving from doppler via gRPC context canceled
2018/10/16 07:34:44.509422 Error while reading from stream (10.244.0.142:8082): rpc error: code = Canceled desc = context canceled
2018/10/16 07:34:44.509463 Disconnecting from stream (10.244.0.142:8082) (doppler.disconnect=false) (ctx.disconnect=1)
```

This has been true for very long time and still reproducible in the latest cf-deployment. While it seems to be harmless it is still noisy and destructs from something that might be important to take into account when debugging.

**Comment by bradylove** [comment]
This issue has been resolved. Closing the issue.
