### ISSUE TITLE
Stream endpoint: filter option

### ISSUE THREAD

**Issue by samu** [cloudfoundry/loggregator#56]
The `/stream` endpoint currently allows to pass `appID` as an argument. It would be useful if in addition to that, the message type could be specified (Log or Metric).

A quick look at the code shows that [here](https://github.com/cloudfoundry/loggregator/blob/cc584703d8c19d660d045295e188d754c4d82bc2/trafficcontroller/internal/proxy/stream_handler.go#L47) the appID is used as a parameter. The [Filter](https://github.com/cloudfoundry/loggregator/blob/b5b9368126d6f49290145cbf6537081690ec347b/plumbing/grpc.proto#L28) structure appears to also allow for are Message option. Is it possible to extend this endpoint so one could specify it as a parameter?

**Comment by bradylove** [comment]
Hi @samu, 

What you desire can be achieved today via the RLP (Reverse Log Proxy) Gateway. The RLP Gateway provides the Loggregator V2 API over HTTP using Server Sent Events with JSON payloads of the Loggregator V2 Envelope Batches.

The RLP Gateway is documented [here](https://github.com/cloudfoundry/loggregator/blob/master/docs/rlp_gateway.md) and the Loggregator V2 Envelope Batch is defined in [loggregator-api](https://github.com/cloudfoundry/loggregator-api/blob/master/v2/envelope.proto#L24)

I am going to close this issue for now. If the RLP Gateway does not fulfil your needs feel free to re-open.
