### ISSUE TITLE
/set-cookie endpoint: HttpOnly

### ISSUE THREAD

**Issue by samu** [cloudfoundry/loggregator#59]
The doppler _/set-cookie_ endpoint returns with a `Set-Cookie` Header in the response, without the `HttpOnly` flag set. The respective code can be found [here](https://github.com/cloudfoundry/loggregator/blob/eadf30b927bd58a056b718ac35c9278ba83da2de/trafficcontroller/internal/proxy/set_cookie_handler.go#L23).

For security reasons it can make sense to set this flag. Do you think it should be included? According to [GO's documentation](https://golang.org/pkg/net/http/#Cookie), setting this flag would be possible.

**Comment by johannasmith** [comment]
@ajackson It exists for consumers to validate authentication before opening a streaming connection.

**Comment by samu** [comment]
As Johanna points out, we consume the _/stream_ endpoint in order to show logs for apps in our IaaS Portal. Since this streaming endpoint is served under a different domain than where the portal is served from (the portal is served under, say, _portal.our-domain.com_, while the streaming endpoint is _doppler.our-domain.com_), we need to make the browser set a session cookie for that streaming domain.

Therefor, we call the _/set-cookie_ endpoint, which is an Ajax POST request and contains the authentication token we received from the UAA endpoint. Via the Set-Cookie Header, authentication against this endpoint is now ensured for the rest of the session.

I'm a bit confused by this header though. According to [this](https://www.owasp.org/index.php/HttpOnly) documentation, HttpOnly is ignored for Ajax requests:

> However, there is currently no prevention of reading or writing the session cookie via a XMLHTTPRequest.

This doesn't make a lot of sense to me and i'm not sure if this documentation is up to date.

**Comment by samu** [comment]
I did some further investigations on this. HttpOnly seems to be taken into account also for Ajax requests.

However, after giving this another thought, i believe the problem described here is a non-issue, at least for our use case. Since the cookie is set for a different domain, it is not possible to steal the cookie via an XSS attack:

The cookie is set for domain _doppler.our-domain.com_, while _portal.our-domain.com_ is where the web application is served from. Assuming that the doppler domain does not serve any endpoints which are vulnerable to XSS attacks, it is only the web portal domain that _might_ be serving content vulnerable to XSS attacks - however, it is in our control if cookies are set for this domain or not. Therefor it is irrelevant if HttpOnly is set on the _/set-cookie_ endpoint or not.

**In any case, i don't see a reason why HttpOnly should _not_ be set.** The cookie clearly stores sensitive information, which shouldn't be accessible via JavaScript (it is accessible through either `getAllResponseHeaders()` or `document.cookie`).

**Comment by heycait** [comment]
This was added in loggregator-release 105.3 https://github.com/cloudfoundry/loggregator-release/releases/tag/v105.3
