### ISSUE TITLE
Error in doppler's README.md

### ISSUE THREAD

**Issue by mmc2004jp** [cloudfoundry/loggregator#62]
Doppler's README.md (https://github.com/cloudfoundry/loggregator/blob/develop/src/doppler/README.md) has a description below:
> In a redundant CloudFoundry setup, Loggregator can be configured to survive zone failures. Log messages from non-affected zones will still make it to the end user. On AWS, availability zones could be used as redundancy zones. The following is an example of a multi zone setup with two zones.

2 points:
1. There is no image after the description. Therefore the sentence "The following is an example of a multi zone setup with two zones." should be removed, or an image (`![Loggregator Diagram](../../docs/loggregator_multizone.png)`) should be added.
2. The same description is in https://github.com/cloudfoundry/loggregator/blob/develop/README.md as well, with expected image.

So why don't we delete the description from the Doppler's README.md?

**Comment by roxtar** [comment]
Thank you @mmc2004jp . We have fixed the issue in the README in commit https://github.com/cloudfoundry/loggregator/commit/32189ed8ef36a9b0190f13f5dcafc826d0a098ba
