### ISSUE TITLE
cf logs --recent fails when app sent very long log message

### ISSUE THREAD

**Issue by stephanme** [cloudfoundry/loggregator#63]
Users complain that they can't get logs with 'cf logs --recent'.  Instead they receive the error message: unknown issue when making HTTP request to Loggregator

We managed to reproduce this problem and seem to happen when an app sends a very long log message (> 4M).

We run cf-deployment 7.5.0 and I used cf cli version 6.43.0+815ea2f3d.2019-02-20.

How to reproduce:

ssh into any application, find the app process and send a very long log message to stdout of this process:

```
cf ssh env

# find app
vcap@733a8b1a-9deb-46f7-6907-1cbe:~$ ps -ef | grep node
vcap          14       0  0 Mar20 ?        00:00:09 node app.js
vcap         166     126  0 12:49 pts/0    00:00:00 grep --color=auto node
# simulate very large log msg (> 4M)
vcap@733a8b1a-9deb-46f7-6907-1cbe:~$ head -c 4200000 < /dev/zero | tr '\0' '\142' > /proc/14/fd/1
vcap@733a8b1a-9deb-46f7-6907-1cbe:~$ echo > /proc/14/fd/1
```

Now try to fetch the logs via cf cli:
```
stephan@WDFN34095835A:/mnt/c/Temp$ cf logs env --recent
Retrieving logs for app env in org uptime / space uptimeci as D047883...

unknown issue when making HTTP request to Loggregator
FAILED
```

I found the following related logs:
```
<14>1 2019-03-28T12:48:53.39147Z 10.0.129.11 gorouter rs2 - [instance@47450 director="bosh-aws-canary" deployment="cf" group="router" az="z2" id="264eb606-bf80-4105-8915-a740ada88d92"] doppler.cf.sap.hana.ondemand.com:443 - [2019-03-28T12:48:53.090+0000] "GET /apps/18a2d3b6-db48-46e9-891e-8f45a1b26c83/recentlogs HTTP/1.1" 500 0 103 "-" "Go-http-client/1.1" "-" "10.0.65.111:8081" x_forwarded_for:"-" x_forwarded_proto:"https" vcap_request_id:"339904c8-a39c-4e0b-4db9-a00df9019552" response_time:0.105424192 app_id:"-" app_index:"-" x_correlationid:"-" x_b3_traceid:"0b0baf73c352d805" x_b3_spanid:"0b0baf73c352d805" x_b3_parentspanid:"-"

<14>1 2019-03-28T12:48:53.525362Z 10.0.65.111 loggregator_trafficcontroller rs2 - [instance@47450 director="bosh-aws-canary" deployment="cf" group="log-api" az="z1" id="26b4222f-9239-44d3-ae72-94ba64a24e03"] 2019/03/28 12:48:53.195045 error communicating with log cache: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5301241 vs. 4194304)
```

Expected behavior:
cf logs --recent should not fail. It may not show log messages >4M but it should show any other available logs.

**Comment by chentom88** [comment]
@stephanme This was actually reported and addressed in: https://github.com/cloudfoundry/loggregator-release/issues/387https://github.com/cloudfoundry/loggregator-release/issues/387. The fix was released in loggregator 105.0 which you should be able to get by upgrading to cf-d v7.6.0. Please give that a try and let us know if the issue persists. Thanks.
