### ISSUE TITLE
It is not possible to forward RSyslog to several hosts

### ISSUE THREAD

**Issue by juanluisvaladas** [cloudfoundry/loggregator#63]
RSyslog allows to failover syslog servers by adding additional servers if the primary fails but Cloud Foundry only allows one server.

This means the log collector must provide redundacy on its own.

**Comment by dsabeti** [comment]
Are you talking about syslog forwarding for CF component logs or application logs?

**Comment by juanluisvaladas** [comment]
CF component logs.

More accurately I mean the logs collected by the local rsyslog server, the configuration file of this server is /etc/rsyslog.conf and is generated with loggregator/bosh/jobs/metron_agent/templates/syslog_forwarder.conf.erb

**Comment by roxtar** [comment]
We have added a `fallback_addresses` property to the metron spec which can be used to specify failover servers.

https://github.com/cloudfoundry/loggregator/blob/develop/bosh/jobs/metron_agent/spec#L21-L23

Closing.
