### ISSUE TITLE
Syslog Sink throttled to 1 message per millisecond

### ISSUE THREAD

**Issue by EngineerBetter** [cloudfoundry/loggregator#66]
The `ExponentialRetryStrategy` is [defaulting to a delay of 1ms](https://github.com/cloudfoundry/loggregator/blob/d648809112be62df9663ac82a7bd39babc47fa28/src/doppler/sinks/retrystrategy/retry_strategy.go#L14). 

If I'm reading the code correctly, the [use of this strategy in `SyslogSink`](https://github.com/cloudfoundry/loggregator/blob/d648809112be62df9663ac82a7bd39babc47fa28/src/doppler/sinks/syslog/syslog_sink.go#L94) means that each iteration of the loop starts with a 1ms delay. If this is the case, then surely the loop should be timed that it only delays if a connection has failed, instead of delaying up-front?

I haven't been able to find the code that deals with incoming messages, but if it is not also throttled in the same manner then this would explain why the `TruncatingBuffer` is filling so easily.

**Comment by ajackson** [comment]
This does indeed look like a problem.   Thanks for pointing that out.   If we simply return 0 when the counter is 0 that should address the issue if I'm reading the code correctly.   This assumes my reading of timer.Reset correctly handling a duration of 0 as safe is also correct.  Do you see a better alternative?

**Comment by EngineerBetter** [comment]
Hey @ajackson, thanks for picking this up. 

I've not really done any Go since leaving the London Services team last year, so I may not be the best person to ask! Your solution is pretty much what I was thinking. I can imagine the safety of timer.Reset being pretty easy to test, but proving that this is one of the reasons that `TruncatingBuffer`s get backed up might be a bit more tricky.

Maybe the select on the timer channel should also come at the end of the `for` instead of the beginning?

**Comment by EngineerBetter** [comment]
@ajackson Looks like the logic has been changed to only invoke the retry delay if the connection failed, which is great. I'm going to go ahead and raise the PR anyway, as firstly I've already done the work, and secondly it may prevent the backoff being accidentally mis-used in the future.

https://github.com/cloudfoundry/loggregator/pull/71

**Comment by roxtar** [comment]
We have addressed this issue. See discussion in #71
