### ISSUE TITLE
TruncatingBuffer is unnecessarily fragile

### ISSUE THREAD

**Issue by EngineerBetter** [cloudfoundry/loggregator#67]
`TruncatingBuffer` drops the whole buffer when full. This seems needlessly fragile, making a small change in workload (one extra message) have a far more destructive impact than it needs to.

A less fragile implementation would discard the newest messages as they arrive. This approach would be better than discarding those at the front of the queue, as the older messages may have information that 'leads up to' the blockage.

An antifragile solution would dynamically resize the buffer when it approaches capacity, up to a larger and more sensible limit.

**Comment by ajackson** [comment]
TruncatingBuffer is used as a "circuit breaker" to prevent server backup and slowdown when we have slow consumers.   

You are correct in that resizing the buffer would be a much more antifragile solution.   However it is so only in the case for a single client.   In the case of the server that has many (as in 1-10K+) of these buffers, resizing the buffer will place severe memory constraints on the server and make it's memory usage very unpredictable.   This will result in loss of service for not just one but many to all of the clients.   

Discarding the newest messages as they arrive is another great strategy.  In our environments we usually see either clients that keep up or clients that can't. This is usually by a large margin.   In the case where we only drop one of the messages, we don't see an ability for the client to catch backup and actually receive the messages.  We took the approach of dropping all the messages but the warning message as this gives the client a chance to catch back up with the incoming messages.

**Comment by EngineerBetter** [comment]
Thanks for the reply.

Consider the following:
* Let MAX_MESSAGE_BYTES by the maximum amount of RAM required to store a message in a buffer (no idea if such a limit is feasible, but the rest of this approach hinges on it!)
* Let MIN_SPARE_BUFFERS equal the number of minimally-sized buffers you want to reserve RAM for
* Let MIN_BUFFER_SIZE be the declared minimum size of a buffer.
* Let VM_RAM be the available RAM, calculated in the control script
* Let ACTIVE_BUFFERS be the number of buffers in use
* Buffers could be allowed to grow to (VM_RAM / ACTIVE_BUFFERS / MAX_MESSAGE_BYTES) - (MIN_BUFFER_SIZE * MAX_MESSAGE_BYTES * MIN_SPARE_BUFFERS)
* A new buffer is required (presumably a new sink appears), and if there is spare RAM, we just create one
* When a new buffer is required but that would encroach into the amount of RAM required for MIN_SPARE_BUFFERS, _then_ and only then do we truncate the existing buffers and reduce their max capacity.

This way the server is always able to use its full capacity, and the only apps that get penalised (ie have their buffers truncated) are those that would have been over the limit under the original algorithm anyway.

MIN_SPARE_BUFFERS would be settable by operators, so they can estimate the amount of headroom they need based on the velocity of new apps and sinks being registered.

Does the above make sense? Kinda hard to explain with the written word, and I got pulled into a meeting halfway through!

**Comment by dsabeti** [comment]
We would like to get more concrete data that changing the buffer size dynamically would help slower consumer, while having predictable memory load on the dopplers. 

In the meantime, we have already made the truncating buffer size configurable from the bosh manifest. Hopefully this helps to solve the problem to some degree.

**Comment by roxtar** [comment]
We are closing this issue for now. If you have further comments, we can reopen and continue the discussion.
