### ISSUE TITLE
Router uses loggregator-api for egress but not ingress

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/loggregator#7]
The router has defined a unique ingress API (via [doppler.proto](https://github.com/cloudfoundry/loggregator/blob/b3c731971be59594ead33eef4d13b16b41182386/plumbing/v2/doppler.proto)). 

Looking at the API, it is nearly identical to the one defined in [loggregator-api](https://github.com/cloudfoundry/loggregator-api/blob/53ff12516dd89c51757f8768945dc4932d46a175/v2/ingress.proto). Deprecating the current API in favor of the loggregator-api one would enable a few things:

1. simpler migration for bringing in go-loggregator
1. agent free ingress to Loggregator system (might be important for k8s)

**Comment by bradylove** [comment]
We have added the `loggregator-api` API to the router.
