### ISSUE TITLE
No healthy messages from Doppler and TrafficController anymore

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/loggregator#72]
With change https://github.com/cloudfoundry/loggregator/commit/8325aa7ac0254441b283afa60589ae77fbf5cbf5 the collectorregistrar was removed from the TrafficController. I didn't find the concrete change, but I assume there is a similar change for Doppler as well.

These registration messages are not only used for the collector checking /varz endpoints, but also for checking /healthz.

It seems that there is no replacement for the /healthz endpoint registration - therefore, we don't get `healthy` metrics for the Doppler and TrafficController components anymore. Can we get the `healthy` metric back, plz?

**Comment by dsabeti** [comment]
We suggest that you rely on the BOSH health metrics to know about component health. As we move components away from the collector, we expect the healthz endpoints to go away.
