### ISSUE TITLE
Read from doppler

### ISSUE THREAD

**Issue by Yancey1989** [cloudfoundry/loggregator#79]
How can i read all data stream from doppler? for example, i want to read all data from router?

**Comment by roxtar** [comment]
I have [responded to your question](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/6Z22H3EFODXK6YVV6RW4F7MP6LFGGIHU/) on the cf-dev mailing list. Basically you can use the Consumer.Firehose method to consume all the data coming from the firehose.

If you want to read data coming only from the router, you would look at the origin of each message and filter those which say router.

If you have more questions, let's continue the discussion on the mailing list. Closing the issue.
