### ISSUE TITLE
syslog-tls and https log drains should support TLS mutual authentication

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/loggregator#90]
We have a number of users that would like to use TLS mutual authentication with their syslog drains but doppler doesn't currently support that use case. Would you be willing to accept a pull request to add the support?

Our proposal is to use the credentials map from the user provided service definition to hold the client certificate, private key, and (optionally) a certificate chain for the drain. When these properties are provided, we will carry them into doppler and use them to setup the `tls.Config` properly for the handshake, mutual auth, and certificate verification.

This would require an updated `syslog_drain_urls` API in the cloud controller and some changes to the syslog drain binder, the TLS writer, the HTTPS writer, and some ancillary plumbing.

**Comment by Jim-Campbell** [comment]
Hi Matthew,

We're currently at work implementing this between Metron and Doppler so we
understand your desire. I'll work with the team in our backlog grooming
sessions to see how pulling that in that falls into our priority scheme.

Thanks,
Jim
Loggregator PM

On Wed, Oct 14, 2015 at 1:44 PM, cf-gitbot <notifications@github.com> wrote:

> We have created an issue in Pivotal Tracker to manage this. You can view
> the current status of your issue at:
> https://www.pivotaltracker.com/story/show/105702626.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/loggregator/issues/90#issuecomment-148172609>
> .
>



-- 
Jim Campbell
Product Manager
Pivotal Labs

**Comment by Jim-Campbell** [comment]
I should be clearer - we're will to look at bringing in your PR when it's
ready and reviewed, but might schedule it via order in our backlog to fit
in with our other plans.

On Wed, Oct 14, 2015 at 1:57 PM, Jim Campbell <jcampbell@pivotal.io> wrote:

> Hi Matthew,
>
> We're currently at work implementing this between Metron and Doppler so we
> understand your desire. I'll work with the team in our backlog grooming
> sessions to see how pulling that in that falls into our priority scheme.
>
> Thanks,
> Jim
> Loggregator PM
>
> On Wed, Oct 14, 2015 at 1:44 PM, cf-gitbot <notifications@github.com>
> wrote:
>
>> We have created an issue in Pivotal Tracker to manage this. You can view
>> the current status of your issue at:
>> https://www.pivotaltracker.com/story/show/105702626.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cloudfoundry/loggregator/issues/90#issuecomment-148172609>
>> .
>>
>
>
>
> --
> Jim Campbell
> Product Manager
> Pivotal Labs
>



-- 
Jim Campbell
Product Manager
Pivotal Labs

**Comment by Jim-Campbell** [comment]
Closed, waiting for PR

**Comment by mvohlken** [comment]
Hello, I'm interested in this feature too. Was the pull request ever submitted and approved?

**Comment by Jim-Campbell** [comment]
No.

**Comment by Jim-Campbell** [comment]
No.
