### ISSUE TITLE
TLS certificate verification config for user syslog drains should be separate from internal endpoints

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/loggregator#91]
The user provided syslog-tis and https sinks are configured to ignore certificate validation whenever the `ssl.skip_cert_verify` property is set in the bosh deployment. Within cf-release, that property is intended to be set when the haproxy or ELB is configured with a self-signed certificate and is needed to allow communication within the deployment in that scenario. Generally speaking, that deployment configuration should not impact the certificate verification performed when an application talks to a third party syslog drain.

Certificate verification for syslog sinks should really have its own control point that is separate and distinct from the deployment's `ssl.skip_cert_verify` property. Ideally this is something the end user could control when defining the user provided service.

**Comment by Jim-Campbell** [comment]
Team says it's valid. We'll pull the bug into our backlog as part of
regular grooming.

On Wed, Oct 14, 2015 at 2:05 PM, cf-gitbot <notifications@github.com> wrote:

> We have created an issue in Pivotal Tracker to manage this. You can view
> the current status of your issue at:
> https://www.pivotaltracker.com/story/show/105704268.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/loggregator/issues/91#issuecomment-148180165>
> .
>



-- 
Jim Campbell
Product Manager
Pivotal Labs
