### ISSUE TITLE
Metron agent doesn't build on Windows

### ISSUE THREAD

**Issue by jvshahid** [cloudfoundry/loggregator#94]
Loggregatorlib used to be able to build under Windows, and with the recent change in 80d688eca0e1d5b9e8a75ca386ae7bdb43d1435f we seemed to have dropped the ability to compile since we didn't carry across the fake Windows implementation from https://github.com/cloudfoundry/loggregatorlib/blob/2b68a3305af889947f0f8c11d0aca4817621f983/cfcomponent/logging_windows.go

Maybe we need to get CI for this project on Windows, since the Garden Windows team depends on it.

**Comment by Jim-Campbell** [comment]
Fixed
