### ISSUE TITLE
syslog_drain_binder does not report instance number

### ISSUE THREAD

**Issue by ramelito** [cloudfoundry/loggregator#97]
Hi, using syslog_drain_binder i noticed it does not report instance number (as cli does it for me)
159 <14>1 2015-11-09T12:03:52.628411+00:00 loggregator b563cf61-a5ba-4540-9734-7ee0e4c5add4 [APP] - - sun.java.mem=1507328 #timestamp=Mon Nov 09 12:03:52 UTC 2015
170 <14>1 2015-11-09T12:03:52.628524+00:00 loggregator b563cf61-a5ba-4540-9734-7ee0e4c5add4 [APP] - - sun.java.heap.committed=1507328 #timestamp=Mon Nov 09 12:03:52 UTC 2015
164 <14>1 2015-11-09T12:03:52.628477+00:00 loggregator b563cf61-a5ba-4540-9734-7ee0e4c5add4 [APP] - - sun.java.mem.free=1113654 #timestamp=Mon Nov 09 12:03:52 UTC 2015
161 <14>1 2015-11-09T12:03:52.628492+00:00 loggregator b563cf61-a5ba-4540-9734-7ee0e4c5add4 [APP] - - sun.java.processors=32 #timestamp=Mon Nov 09 12:03:52 UTC 2015

cf cli reports this as e.g. [APP/0]

Is it a bug or there are some knobs to tune this?

**Comment by ramelito** [comment]
https://github.com/cloudfoundry/loggregator/blob/bb67dc9f78d6be921b0d242f90fb86e8e4bbbbb1/src/doppler/sinks/syslogwriter/writer.go#L57

as i can understand doppler is waiting for 'App' not 'APP' to print instance number, i suppose this is a bug

**Comment by Jim-Campbell** [comment]
Hi @ramelito we agree and have moved your issue fairly high in our [backlog](https://www.pivotaltracker.com/n/projects/993188)

**Comment by Jim-Campbell** [comment]
Fixed and releasing in CF V227
