### ISSUE TITLE
Include updated loggregator diagram with syslog configuration

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/loggregator#99]
It would be nice to show that metron configures VMs to forward syslog to some destination.

![](https://cloud.githubusercontent.com/assets/185847/11315463/05698c0a-8fa7-11e5-9e41-d7e0cda021b0.png)

**Comment by Jim-Campbell** [comment]
How about this?

![logging metrics overview](https://cloud.githubusercontent.com/assets/13769968/11350280/03521c68-91ee-11e5-9666-d7936b27c491.png)

**Comment by tcnksm** [comment]
Nice !

**Comment by Jim-Campbell** [comment]
Doc updated
